//! `locales/en.yml` → one Rust module per section, one function per key, for a
//! crate's `build.rs` to write into `OUT_DIR`. Also the en/ko checks every
//! crate that owns a locale runs, so a missing translation fails a test
//! instead of silently falling back to English.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

/// One `en.yml` key: its doc lines (the `#` comments directly above it) and
/// the placeholders its value interpolates, in order of first appearance.
pub struct Key {
    pub name: String,
    pub doc: Vec<String>,
    pub params: Vec<String>,
}

pub fn generate(en: &str, custom_dir: &Path) -> Result<String, String> {
    let mut out = String::from("// @generated by strings_gen from locales/en.yml\n");
    let mut seen_custom = BTreeSet::new();
    for (section, keys) in parse(en)? {
        let custom_file = custom_dir.join(format!("{section}.rs"));
        let overrides = match std::fs::read_to_string(&custom_file) {
            Ok(text) => {
                seen_custom.insert(section.clone());
                custom_fn_names(&text)
            }
            Err(_) => BTreeSet::new(),
        };
        writeln!(out, "pub mod {section} {{").unwrap();
        if custom_file.exists() {
            writeln!(out, "    pub(crate) use super::custom::{section}::*;").unwrap();
        }
        for key in keys {
            if overrides.contains(&key.name) {
                continue;
            }
            for line in &key.doc {
                writeln!(
                    out,
                    "    ///{}",
                    if line.is_empty() {
                        String::new()
                    } else {
                        format!(" {line}")
                    }
                )
                .unwrap();
            }
            let sig: Vec<_> = key
                .params
                .iter()
                .map(|p| format!("{p}: impl std::fmt::Display"))
                .collect();
            let args: String = key.params.iter().map(|p| format!(", {p} = {p}")).collect();
            writeln!(
                out,
                "    pub(crate) fn {}({}) -> String {{",
                key.name,
                sig.join(", ")
            )
            .unwrap();
            writeln!(
                out,
                "        rust_i18n::t!(\"{section}.{}\"{args}).into_owned()",
                key.name
            )
            .unwrap();
            writeln!(out, "    }}").unwrap();
        }
        writeln!(out, "}}").unwrap();
    }
    // A custom file whose section does not exist would be silently ignored.
    if let Ok(dir) = std::fs::read_dir(custom_dir) {
        for entry in dir.flatten() {
            let path = entry.path();
            let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            if stem != "mod" && !seen_custom.contains(stem) {
                return Err(format!("{} names no section", path.display()));
            }
        }
    }
    Ok(out)
}

/// The flat two-level shape `en.yml` keeps: `section:` at column 0, then
/// `  key: value` (a `|-` block value continues on deeper-indented lines).
pub fn parse(en: &str) -> Result<Vec<(String, Vec<Key>)>, String> {
    let mut sections: Vec<(String, Vec<Key>)> = Vec::new();
    let mut doc: Vec<String> = Vec::new();
    let mut lines = en.lines().enumerate().peekable();
    while let Some((n, line)) = lines.next() {
        if line.trim().is_empty() {
            doc.clear();
        } else if let Some(c) = line.strip_prefix("  #") {
            doc.push(c.trim().to_string());
        } else if line.starts_with('#') {
            doc.clear();
        } else if let Some(section) = line.strip_suffix(':').filter(|_| !line.starts_with(' ')) {
            check_ident(section, n)?;
            sections.push((section.to_string(), Vec::new()));
            doc.clear();
        } else if let Some(rest) = line.strip_prefix("  ").filter(|r| !r.starts_with(' ')) {
            let (name, value) = rest
                .split_once(':')
                .ok_or(format!("line {}: no `:`", n + 1))?;
            check_ident(name, n)?;
            let mut value = value.to_string();
            while let Some((_, next)) = lines.peek() {
                if !next.starts_with("    ") {
                    break;
                }
                value.push_str(next);
                lines.next();
            }
            let section = sections
                .last_mut()
                .ok_or(format!("line {}: key outside a section", n + 1))?;
            let params = placeholders(&value);
            for p in &params {
                check_ident(p, n)?;
            }
            section.1.push(Key {
                name: name.to_string(),
                doc: std::mem::take(&mut doc),
                params,
            });
        } else {
            return Err(format!("line {}: unexpected shape: {line}", n + 1));
        }
    }
    Ok(sections)
}

fn placeholders(value: &str) -> Vec<String> {
    let mut found = Vec::new();
    let mut rest = value;
    while let Some(start) = rest.find("%{") {
        let tail = &rest[start + 2..];
        let Some(end) = tail.find('}') else { break };
        let name = tail[..end].to_string();
        if !found.contains(&name) {
            found.push(name);
        }
        rest = &tail[end + 1..];
    }
    found
}

/// Names that become a Rust identifier as-is: lowercase snake case, not a keyword.
fn check_ident(name: &str, line: usize) -> Result<(), String> {
    const KEYWORDS: &[&str] = &[
        "as", "async", "await", "box", "break", "const", "continue", "crate", "do", "dyn", "else",
        "enum", "extern", "false", "fn", "for", "gen", "if", "impl", "in", "let", "loop", "match",
        "mod", "move", "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait",
        "true", "try", "type", "unsafe", "use", "where", "while", "yield",
    ];
    let shaped = name.chars().next().is_some_and(|c| c.is_ascii_lowercase())
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
    if !shaped || KEYWORDS.contains(&name) {
        return Err(format!(
            "line {}: `{name}` cannot be a Rust identifier",
            line + 1
        ));
    }
    Ok(())
}

/// `pub(crate) fn name` items of a custom file — each replaces its key.
fn custom_fn_names(text: &str) -> BTreeSet<String> {
    text.lines()
        .filter_map(|l| l.strip_prefix("pub(crate) fn "))
        .filter_map(|rest| {
            rest.split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
                .next()
        })
        .map(str::to_string)
        .collect()
}

/// Every dotted key (`section.key`) whose value is a scalar, with the
/// `%{placeholder}` names it interpolates.
fn leaves(yaml: &str) -> Result<std::collections::BTreeMap<String, BTreeSet<String>>, String> {
    fn walk(
        value: &yaml_serde::Value,
        prefix: &str,
        out: &mut std::collections::BTreeMap<String, BTreeSet<String>>,
    ) {
        match value {
            yaml_serde::Value::Mapping(map) => {
                for (k, v) in map {
                    let key = k.as_str().unwrap_or("<non-string-key>");
                    let path = if prefix.is_empty() {
                        key.to_string()
                    } else {
                        format!("{prefix}.{key}")
                    };
                    walk(v, &path, out);
                }
            }
            yaml_serde::Value::String(text) => {
                let mut names = BTreeSet::new();
                let mut rest = text.as_str();
                while let Some(open) = rest.find("%{") {
                    rest = &rest[open + 2..];
                    let Some(close) = rest.find('}') else { break };
                    names.insert(rest[..close].trim().to_string());
                    rest = &rest[close + 1..];
                }
                out.insert(prefix.to_string(), names);
            }
            _ => {
                out.insert(prefix.to_string(), BTreeSet::new());
            }
        }
    }
    let value: yaml_serde::Value = yaml_serde::from_str(yaml).map_err(|e| e.to_string())?;
    let mut out = std::collections::BTreeMap::new();
    walk(&value, "", &mut out);
    Ok(out)
}

/// Every key in `en` has a counterpart in `ko` and the reverse. A missing
/// translation silently falls back to English, so drift has to fail a test.
pub fn check_key_parity(en: &str, ko: &str) -> Result<(), String> {
    let en = leaves(en)?;
    let ko = leaves(ko)?;
    let missing_in_ko: Vec<_> = en.keys().filter(|k| !ko.contains_key(*k)).collect();
    let missing_in_en: Vec<_> = ko.keys().filter(|k| !en.contains_key(*k)).collect();
    if missing_in_ko.is_empty() && missing_in_en.is_empty() {
        return Ok(());
    }
    Err(format!(
        "i18n key drift between en.yml and ko.yml:\n  missing in ko.yml: {missing_in_ko:?}\n  missing in en.yml: {missing_in_en:?}"
    ))
}

/// A key both files carry interpolates the same placeholders in each.
/// `rust_i18n` substitutes by name, so a translation that renamed or dropped
/// one compiles and renders a literal `%{name}` to that locale's users.
pub fn check_placeholder_parity(en: &str, ko: &str) -> Result<(), String> {
    let en = leaves(en)?;
    let ko = leaves(ko)?;
    let mismatched: Vec<String> = en
        .iter()
        .filter_map(|(key, en_names)| {
            let ko_names = ko.get(key)?;
            (en_names != ko_names).then(|| format!("{key}: en {en_names:?} vs ko {ko_names:?}"))
        })
        .collect();
    if mismatched.is_empty() {
        return Ok(());
    }
    Err(format!(
        "i18n placeholder drift between en.yml and ko.yml:\n  {}",
        mismatched.join("\n  ")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The `#` lines directly above a key are its doc; a blank line ends them,
    /// so a group header standing on its own documents nothing.
    #[test]
    fn only_comments_touching_a_key_document_it() {
        let en = "menu:\n  # File menu\n\n  # Opens a window.\n  new_window: \"New\"\n  open: \"Open\"\n";
        let sections = super::parse(en).expect("parses");
        let keys = &sections[0].1;
        assert_eq!(keys[0].name, "new_window");
        assert_eq!(keys[0].doc, ["Opens a window."]);
        assert!(keys[1].doc.is_empty());
    }

    /// Placeholders become parameters once each, in the order the English value
    /// first names them — a `|-` block value included.
    #[test]
    fn placeholders_become_parameters_in_first_use_order() {
        let en = "flow:\n  a: \"%{node} then %{n}, %{node} again\"\n  b: |-\n    first %{x}\n    then %{y}\n";
        let sections = super::parse(en).expect("parses");
        assert_eq!(sections[0].1[0].params, ["node", "n"]);
        assert_eq!(sections[0].1[1].params, ["x", "y"]);
    }

    /// A key that cannot be spelled as a Rust function fails the build by name
    /// rather than generating code that does not compile.
    #[test]
    fn a_key_that_is_not_an_identifier_is_refused() {
        for en in [
            "git:\n  type: \"x\"\n",
            "git:\n  7day: \"x\"\n",
            "git:\n  a: \"%{Name}\"\n",
        ] {
            let err = super::parse(en).err().expect("refused");
            assert!(err.contains("Rust identifier"), "{err}");
        }
    }

    /// A custom function named like a key replaces the generated one, and a
    /// custom file whose section does not exist is refused.
    #[test]
    fn a_custom_function_replaces_its_key() {
        let dir = tempfile::tempdir().expect("tempdir");
        std::fs::write(
            dir.path().join("flow.rs"),
            "pub(crate) fn pin(n: usize) -> String {\n    n.to_string()\n}\n",
        )
        .expect("write");
        let out = super::generate("flow:\n  pin: \"%{n}\"\n  stop: \"Stop\"\n", dir.path())
            .expect("generates");
        assert!(
            out.contains("pub(crate) use super::custom::flow::*;"),
            "{out}"
        );
        assert!(!out.contains("fn pin("), "{out}");
        assert!(out.contains("fn stop()"), "{out}");

        std::fs::write(dir.path().join("nowhere.rs"), "").expect("write");
        let err = super::generate("flow:\n  stop: \"Stop\"\n", dir.path()).expect_err("refused");
        assert!(err.contains("names no section"), "{err}");
    }

    /// A platform-only override must not leave an unconditional generated
    /// function behind on targets where the custom function is absent.
    #[test]
    fn platform_gated_custom_functions_replace_generated_keys() {
        for condition in ["windows", "target_os = \"linux\"", "target_os = \"macos\""] {
            let dir = tempfile::tempdir().expect("tempdir");
            std::fs::write(
                dir.path().join("menu.rs"),
                format!(
                    "#[cfg({condition})]\npub(crate) fn tray_show() -> String {{\n    String::new()\n}}\n"
                ),
            )
            .expect("write");
            let out = super::generate(
                "menu:\n  tray_show: \"Open\"\n  settings: \"Settings\"\n",
                dir.path(),
            )
            .expect("generates");
            assert!(
                out.contains("pub(crate) use super::custom::menu::*;"),
                "{out}"
            );
            assert!(!out.contains("fn tray_show("), "{out}");
            assert!(out.contains("fn settings()"), "{out}");
        }
    }

    #[test]
    fn a_key_missing_from_either_side_is_reported() {
        let en = "a:\n  x: \"X\"\n  y: \"Y\"\n";
        let ko = "a:\n  x: \"엑스\"\n  z: \"제트\"\n";
        let err = check_key_parity(en, ko).expect_err("drift");
        assert!(err.contains("a.y") && err.contains("a.z"), "{err}");
        assert!(check_key_parity(en, en).is_ok());
    }

    #[test]
    fn a_renamed_placeholder_is_reported() {
        let en = "a:\n  x: \"%{n} items\"\n";
        let ko = "a:\n  x: \"%{count}개\"\n";
        let err = check_placeholder_parity(en, ko).expect_err("drift");
        assert!(err.contains("a.x"), "{err}");
    }
}
