//! Singleton settings window for common daruda config options.
//!
//! Reopening routes through [`SettingsWindow::focus_section`] instead of
//! spawning a duplicate. Builtin sections pair a `BuiltinSection` variant with
//! nav/header strings and a `render_<section>` method.

mod render;
mod sections;

#[cfg(test)]
mod tests;

use std::collections::{HashMap, HashSet};
use std::ops::RangeBounds;

use crate::ui::theme;
use daruda_config::BuiltinSection;
use gpui::{
    Context, Entity, FocusHandle, Focusable as _, IntoElement, SharedString, Subscription, Task,
    Window, WindowBackgroundAppearance, div, prelude::*, px,
};

use crate::surface::strings as s;
use crate::ui::select::{self, SelectOption, SelectState};
use crate::ui::{InputEvent, InputState};
use crate::window_registry::WindowRegistry;

pub struct SettingsWindow {
    panel_focus_handle: FocusHandle,
    /// Open-time snapshot; saves overlay form fields so hidden config survives.
    base_config: daruda_config::Config,
    /// Section currently rendered by the body.
    active_section: BuiltinSection,
    /// Per-section input focus handles, in tab-cycle order. `focus_section`
    /// jumps to the first handle when entering a section from outside the
    /// window (sidebar click, external open); `focus_next_input` cycles the
    /// full list on Tab. Single source for both — previously a first-handle
    /// map plus a separately hand-maintained match in `focus_next_input`,
    /// which could drift out of sync when a field was added.
    section_focus_targets: HashMap<BuiltinSection, Vec<FocusHandle>>,
    // ---- form fields ----
    // General page.
    language_select: Entity<SelectState>,
    // Theme (rendered inside the General page).
    // `terminal_preset_select` controls the cell palette (16-color
    // ANSI + fg/bg); `ui_preset_select` controls the chrome palette
    // (workspace, sidebar, modal, status bar). The two axes are
    // independent — see `daruda_config::ThemeConfig`.
    terminal_preset_select: Entity<SelectState>,
    ui_preset_select: Entity<SelectState>,
    // Font
    font_family_select: Entity<SelectState>,
    font_size_input: Entity<InputState>,
    editor_font_size_input: Entity<InputState>,
    agent_chat_font_size_input: Entity<InputState>,
    vertical_spacing_input: Entity<InputState>,
    horizontal_spacing_input: Entity<InputState>,
    // Cursor
    cursor_style_select: Entity<SelectState>,
    cursor_blinking: bool,
    // Agent
    default_permission_mode_select: Entity<SelectState>,
    agent_preset_select: Entity<SelectState>,
    agent_use_modifier_to_send: bool,
    agent_rows: Vec<AgentCatalogRow>,
    /// Catalog entries with no editable row — a `preset` id daruda cannot
    /// resolve. Carried verbatim from load to save so the editor never silently
    /// deletes an entry it has no fields for. Appended after the editable rows,
    /// which is positionally lossy but semantically not: an entry that resolves
    /// to nothing never takes part in the runtime catalog's ordering.
    agent_unresolved_entries: Vec<daruda_config::AgentEntry>,
    // Accounts (Task 9). Snapshot loaded from `accounts.json` at
    // construction; every write goes through the section's own
    // `set_default_account`/`remove_account` handlers, which persist
    // immediately (no Save-button batching, unlike the config-backed
    // fields above) and broadcast the new state to every open
    // `Workspace` window. See `sections/accounts.rs`'s module doc.
    accounts: daruda_store::accounts::AccountsState,
    // Render
    max_fps_select: Entity<SelectState>,
    // Shell
    close_pane_on_exit: bool,
    // Window
    opacity_input: Entity<InputState>,
    window_blur: bool,
    // Terminal
    scrollback_input: Entity<InputState>,
    inset_x_input: Entity<InputState>,
    inset_y_input: Entity<InputState>,
    // Sidebar
    files_show_hidden: bool,
    files_use_gitignore: bool,
    // File Viewer
    syntax_theme_select: Entity<SelectState>,
    // Clipboard
    clipboard_streaming_input: Entity<InputState>,
    // Panels (bottom-dock macro grid)
    panels_grid_columns_input: Entity<InputState>,
    // Claude Status
    claude_status_enable: bool,
    // Notifications (Telegram)
    telegram_enabled: bool,
    telegram_token_input: Entity<InputState>,
    /// Presence-only cache of whether a token is currently stored in
    /// the Keychain — seeded once at construction, updated by the
    /// Save/Clear button handlers. Never holds the token itself.
    telegram_token_configured: bool,
    /// Transient UI-only state (never persisted): the pairing code
    /// most recently generated by "Generate Pairing Code", shown with
    /// the `/pair <code>` instructions until the window closes.
    telegram_pair_code: Option<String>,
    /// Whether the `/pair <code>` command was just copied — drives the
    /// Copy/Copied! label swap, mirrors `ErrorReportModal::copied`.
    telegram_pair_command_copied: bool,
    /// Reverts `telegram_pair_command_copied` after a short delay.
    /// Re-created on every copy click so a rapid second click resets
    /// the window, mirrors `ErrorReportModal::_copied_revert_task`.
    _telegram_pair_copy_revert_task: Option<Task<()>>,
    scroll_handle: gpui::ScrollHandle,
    _input_subscriptions: Vec<Subscription>,
    error: Option<SharedString>,
    /// Plugin ids (`<plugin>@<marketplace>`) with an `install` /
    /// `uninstall` CLI invocation currently spawned on the
    /// `background_executor`. Used by the Plugin section to show a
    /// transient `Installing…` / `Uninstalling…` label and to swallow
    /// duplicate clicks while the request is in flight.
    pub(super) plugin_ops_in_flight: std::collections::HashSet<String>,
    /// Last plugin-op error message — surfaced inline above the plugin
    /// list. `None` clears the banner.
    pub(super) plugin_last_error: Option<SharedString>,
    /// `<plugin>@<marketplace>` of the plugin whose detail pane is on
    /// the right side of the master-detail layout. `None` shows the
    /// "select a plugin" placeholder.
    pub(super) plugin_selected: Option<String>,
    /// When `Some`, the right pane swaps from the plugin detail to a
    /// SKILL.md viewer. Cleared by the `← Back` button.
    pub(super) plugin_view_skill: Option<PluginSkillView>,
    /// Subscription that calls `cx.notify()` whenever the app-wide
    /// `SkillsState` Global changes — so the Plugin page reflects
    /// install / uninstall completions (and external `claude plugin`
    /// CLI runs) without polling.
    _skills_global_subscription: Subscription,
    /// Subscription that refreshes the `accounts` mirror + repaints whenever
    /// the app-wide `AccountsGlobal` changes — so an add/reauth/default/
    /// delete in any Workspace window shows here without a restart.
    _accounts_global_subscription: Subscription,
    /// Subscription that calls `cx.notify()` whenever the `Updater`
    /// entity changes status — so the About page reflects check /
    /// download / install progress reactively. `None` when the updater
    /// global never registered (unparseable version). Observing the
    /// entity (not the global) is deliberate: the global holder is set
    /// once at init and never replaced, so `observe_global` would never
    /// fire; the entity self-notifies on every status transition.
    _updater_subscription: Option<Subscription>,
}

/// In-Settings SKILL.md viewer state. The body load is async (disk
/// read on the background executor) so the variant tracks the three
/// observable phases — request in flight, body ready, body failed.
#[derive(Clone)]
pub(super) struct PluginSkillView {
    /// `display_name_for_invocation(skill)` — the namespaced form
    /// shown in the header (`<plugin>:<skill>`).
    pub(super) display_name: String,
    /// Absolute path to the SKILL.md file being viewed. Captured at
    /// open time so the async loader knows exactly which file to read
    /// even if the underlying `SkillsState` reshuffles mid-load.
    pub(super) skill_md_path: std::path::PathBuf,
    pub(super) body: PluginSkillBodyState,
}

#[derive(Clone)]
pub(super) enum PluginSkillBodyState {
    Loading,
    Loaded(SharedString),
    Error(SharedString),
}

#[derive(Clone)]
pub(super) struct AgentCatalogRow {
    /// The preset this row references, when it has one. Kept so saving
    /// re-derives the row's overrides against that preset instead of writing a
    /// frozen copy — an untouched field keeps tracking the preset.
    pub(super) preset: Option<String>,
    pub(super) id_input: Entity<InputState>,
    pub(super) name_input: Entity<InputState>,
    /// The command that runs the ACP adapter — `Raw`'s full string, or the
    /// `adapter_command` sub-field when `transport_select` is `ssh`/`docker`.
    pub(super) command_input: Entity<InputState>,
    /// Transport kind for this row: `"raw"` / `"ssh"` / `"docker"` — mirrors
    /// [`daruda_config::AgentLaunch`]'s three variants.
    pub(super) transport_select: Entity<SelectState>,
    /// SSH host — only meaningful (and only rendered) when `transport_select`
    /// is `"ssh"`.
    pub(super) host_input: Entity<InputState>,
    /// Docker container name — only meaningful (and only rendered) when
    /// `transport_select` is `"docker"`.
    pub(super) container_input: Entity<InputState>,
    /// Optional session mode to request when this agent connects, overriding
    /// the global default. Free text: a mode id is whatever the agent
    /// advertises, which varies by agent and by model. Empty = no override.
    pub(super) default_mode_input: Entity<InputState>,
    /// The command's executable name, when [`agent_command_path_warning`]
    /// determined it names a local binary not found on `PATH` — `None` when
    /// no check applies (`npx`/`uvx`/JSON stdio) or the binary was found.
    /// Independent of transport: an ssh/docker row's warning is suppressed at
    /// render time instead (see `sections::agent::render_agent_catalog_row`),
    /// since that needs no fresh `which` lookup. Recomputed on construction
    /// and whenever `command_input` changes (see
    /// [`SettingsWindow::recompute_agent_row_path_warning`]); `which::which`
    /// is I/O, so `render` only ever reads this field, never calls it.
    pub(super) path_warning: Option<String>,
}

impl SettingsWindow {
    pub fn new(window: &mut Window, cx: &mut Context<Self>) -> Self {
        Self::new_with_section(BuiltinSection::default(), window, cx)
    }

    fn subscribe_input_state(
        state: &Entity<InputState>,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Subscription {
        cx.subscribe_in(
            state,
            window,
            |this, _, ev: &InputEvent, window, cx| match ev {
                InputEvent::PressEnter { .. } => this.submit(window, cx),
                InputEvent::Change => {
                    if this.error.is_some() {
                        this.error = None;
                        cx.notify();
                    }
                }
                InputEvent::Focus | InputEvent::Blur => {}
            },
        )
    }

    /// Build a text-input field, wire it to the standard submit /
    /// clear-error subscription, and capture its focus handle — one call
    /// site instead of three separately-located steps (construct, then
    /// subscribe, then extract the handle) for every bounded text field.
    fn new_text_field(
        placeholder: &str,
        default_value: String,
        window: &mut Window,
        cx: &mut Context<Self>,
        subs: &mut Vec<Subscription>,
    ) -> (Entity<InputState>, FocusHandle) {
        let state = cx.new(|cx_state| {
            InputState::new(window, cx_state)
                .placeholder(placeholder)
                .default_value(default_value)
        });
        subs.push(Self::subscribe_input_state(&state, window, cx));
        let fh = state.read(cx).focus_handle(cx);
        (state, fh)
    }

    fn agent_row_from_definition(
        definition: &daruda_config::AgentDefinition,
        preset: Option<String>,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> AgentCatalogRow {
        let id = definition.id.clone();
        let name = definition.name.clone();
        let (command, transport_kind, host, container) = match &definition.launch {
            daruda_config::AgentLaunch::Raw(command) => {
                (command.clone(), "raw", String::new(), String::new())
            }
            daruda_config::AgentLaunch::Ssh {
                adapter_command,
                host,
            } => (adapter_command.clone(), "ssh", host.clone(), String::new()),
            daruda_config::AgentLaunch::Docker {
                adapter_command,
                container,
            } => (
                adapter_command.clone(),
                "docker",
                String::new(),
                container.clone(),
            ),
        };
        let path_warning = agent_command_path_warning(&command);
        let transport_kind = SharedString::from(transport_kind);
        let default_mode = definition.default_mode.clone().unwrap_or_default();
        AgentCatalogRow {
            preset,
            id_input: cx.new(|cx_state| {
                InputState::new(window, cx_state)
                    .placeholder("agent-id")
                    .default_value(id)
            }),
            name_input: cx.new(|cx_state| {
                InputState::new(window, cx_state)
                    .placeholder("Display name")
                    .default_value(name)
            }),
            command_input: cx.new(|cx_state| {
                InputState::new(window, cx_state)
                    .placeholder("command --acp")
                    .default_value(command)
            }),
            transport_select: cx.new(|cx| {
                let opts = vec![
                    SelectOption::new("raw", s::settings_agent_transport_raw()),
                    SelectOption::new("ssh", s::settings_agent_transport_ssh()),
                    SelectOption::new("docker", s::settings_agent_transport_docker()),
                ];
                select::state_with_options(opts, Some(&transport_kind), window, cx)
            }),
            host_input: cx.new(|cx_state| {
                InputState::new(window, cx_state)
                    .placeholder("user@host")
                    .default_value(host)
            }),
            container_input: cx.new(|cx_state| {
                InputState::new(window, cx_state)
                    .placeholder("container-name")
                    .default_value(container)
            }),
            default_mode_input: cx.new(|cx_state| {
                InputState::new(window, cx_state)
                    .placeholder(s::settings_agent_default_mode_placeholder())
                    .default_value(default_mode)
            }),
            path_warning,
        }
    }

    /// Wire one agent-catalog row's inputs to the standard submit /
    /// clear-error subscription plus the transport-pick repaint, pushing
    /// each into `subs`. An associated fn (not `&mut self`) so both the
    /// constructor's initial rows (loaded from config) and rows added at
    /// runtime via [`Self::add_agent_row`] go through the same wiring —
    /// keeping them separate previously let the constructor's copy drift
    /// out of sync and silently drop `default_mode_input`'s subscription.
    fn subscribe_agent_row(
        row: &AgentCatalogRow,
        window: &mut Window,
        cx: &mut Context<Self>,
        subs: &mut Vec<Subscription>,
    ) {
        subs.push(Self::subscribe_input_state(&row.id_input, window, cx));
        subs.push(Self::subscribe_input_state(&row.name_input, window, cx));
        subs.push(Self::subscribe_input_state(&row.command_input, window, cx));
        subs.push(Self::subscribe_input_state(&row.host_input, window, cx));
        subs.push(Self::subscribe_input_state(
            &row.container_input,
            window,
            cx,
        ));
        subs.push(Self::subscribe_input_state(
            &row.default_mode_input,
            window,
            cx,
        ));
        // Re-render on transport pick so the row immediately shows/hides the
        // matching host/container field (rows are added/removed at runtime,
        // unlike the fixed global dropdowns wired in `new_with_section`), and
        // so an ssh/docker pick immediately hides a stale PATH warning — that
        // suppression is transport-dependent but needs no fresh `which` call
        // (see `agent.rs::render_agent_catalog_row`), so a plain repaint
        // suffices here.
        subs.push(cx.subscribe_in(
            &row.transport_select,
            window,
            |_this, _state, ev: &select::ConfirmEvent, _window, cx| {
                if matches!(ev, select::SelectEvent::Confirm(_)) {
                    cx.notify();
                }
            },
        ));
        // Recompute the local-PATH warning whenever the command text changes.
        // Separate from the standard submit/clear-error subscription above,
        // which is shared by every input field and doesn't know which row's
        // command changed.
        subs.push(cx.subscribe_in(
            &row.command_input,
            window,
            |this, state, ev: &InputEvent, _window, cx| {
                if matches!(ev, InputEvent::Change)
                    && let Some(index) = this.agent_row_index_by_command(state)
                {
                    this.recompute_agent_row_path_warning(index, cx);
                }
            },
        ));
    }

    /// Index of the row whose `command_input` is `entity`, if any. Rows are
    /// looked up by entity identity rather than a captured index because
    /// indices shift on [`Self::remove_agent_row`], and this closure is wired
    /// once per row without a stable index to close over.
    fn agent_row_index_by_command(&self, entity: &Entity<InputState>) -> Option<usize> {
        self.agent_rows
            .iter()
            .position(|row| row.command_input == *entity)
    }

    /// Re-run the local-PATH check for one row and store the result. The
    /// `which` lookup is I/O, so this runs from the command-change handler
    /// and construction only — never from `render`, which just reads
    /// [`AgentCatalogRow::path_warning`]. Independent of transport: the
    /// ssh/docker exemption is applied at render time instead, since it needs
    /// no I/O (see `agent.rs::render_agent_catalog_row`).
    fn recompute_agent_row_path_warning(&mut self, index: usize, cx: &mut Context<Self>) {
        let Some(row) = self.agent_rows.get(index) else {
            return;
        };
        let command = row.command_input.read(cx).value().to_string();
        self.agent_rows[index].path_warning = agent_command_path_warning(&command);
        cx.notify();
    }

    /// Append a catalog row. `preset` names the preset `definition` came from
    /// (the "Add Preset" button), so the saved entry references it rather than
    /// copying its fields; `None` adds a custom row.
    pub(super) fn add_agent_row(
        &mut self,
        definition: daruda_config::AgentDefinition,
        preset: Option<String>,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        let row = Self::agent_row_from_definition(&definition, preset, window, cx);
        Self::subscribe_agent_row(&row, window, cx, &mut self._input_subscriptions);
        self.agent_rows.push(row);
        self.error = None;
        cx.notify();
    }

    pub(super) fn remove_agent_row(&mut self, index: usize, cx: &mut Context<Self>) {
        if index < self.agent_rows.len() {
            self.agent_rows.remove(index);
            self.error = None;
            cx.notify();
        }
    }

    pub fn new_with_section(
        active: BuiltinSection,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) -> Self {
        // Defensive idempotent init for test fixtures that open a
        // Settings window without going through `globals::init_all`.
        crate::settings_store::SettingsStore::init(cx);
        let config = crate::settings_store::SettingsStore::global(cx)
            .user()
            .clone();

        // Language select — options driven by the canonical locale list so
        // adding a new locale only requires updating SUPPORTED_LOCALES.
        let lang = SharedString::from(config.general.language.clone());
        let language_select = cx.new(|cx| {
            let opts: Vec<select::SelectOption> = daruda_config::SUPPORTED_LOCALES
                .iter()
                .map(|&slug| {
                    let label = match slug {
                        "auto" => s::settings_language_auto(),
                        "en" => s::settings_language_en(),
                        "ko" => s::settings_language_ko(),
                        other => other.to_owned(),
                    };
                    select::SelectOption::new(slug, label)
                })
                .collect();
            select::state_with_options(opts, Some(&lang), window, cx)
        });

        // Terminal preset select — cell palette (fg/bg + ANSI 16).
        let terminal_preset = SharedString::from(config.theme.terminal_preset.clone());
        let terminal_preset_select = cx.new(|cx| {
            let opts = daruda_config::THEME_PRESETS
                .iter()
                .map(|p| SelectOption::new(p.name, p.display_name))
                .collect();
            select::state_with_options(opts, Some(&terminal_preset), window, cx)
        });

        // UI preset select — chrome palette (workspace, modal, status bar, …).
        let ui_preset = SharedString::from(config.theme.ui_preset.clone());
        let ui_preset_select = cx.new(|cx| {
            let opts = daruda_config::UI_THEME_PRESETS
                .iter()
                .map(|p| SelectOption::new(p.name, p.display_name))
                .collect();
            select::state_with_options(opts, Some(&ui_preset), window, cx)
        });

        let font_names = all_font_names(cx, &config.font.family);
        let font_family = SharedString::from(config.font.family.clone());
        let font_family_select = cx.new(|cx| {
            let opts = font_names
                .iter()
                .map(|n| SelectOption::simple(n.clone()))
                .collect();
            select::state_with_options(opts, Some(&font_family), window, cx)
        });

        // Collected as each field below is built, instead of assembled in one
        // block after the fact — keeps "construct → subscribe → focus handle
        // → section jump target" together per field. `section_focus_targets`
        // is the single source for both `focus_section` (first handle) and
        // `focus_next_input` (full per-section cycle order).
        let mut input_subscriptions: Vec<Subscription> = Vec::new();
        let mut section_focus_targets: HashMap<BuiltinSection, Vec<FocusHandle>> = HashMap::new();

        let (font_size_input, font_size_fh) = Self::new_text_field(
            "e.g. 13",
            format!("{}", config.font.size),
            window,
            cx,
            &mut input_subscriptions,
        );
        section_focus_targets
            .entry(BuiltinSection::Font)
            .or_default()
            .push(font_size_fh);
        // Not wired into the Font tab cycle (kept out of
        // `section_focus_targets`) — only font_size/vertical/horizontal
        // spacing are, matching the pre-existing cycle order.
        let (editor_font_size_input, _) = Self::new_text_field(
            "e.g. 13",
            format!("{}", config.font.editor_size),
            window,
            cx,
            &mut input_subscriptions,
        );
        let (agent_chat_font_size_input, _) = Self::new_text_field(
            "e.g. 13",
            format!("{}", config.font.agent_chat_size),
            window,
            cx,
            &mut input_subscriptions,
        );
        let (vertical_spacing_input, vertical_spacing_fh) = Self::new_text_field(
            "e.g. 1.0",
            format!("{}", config.font.vertical_spacing),
            window,
            cx,
            &mut input_subscriptions,
        );
        section_focus_targets
            .entry(BuiltinSection::Font)
            .or_default()
            .push(vertical_spacing_fh);
        let (horizontal_spacing_input, horizontal_spacing_fh) = Self::new_text_field(
            "e.g. 1.0",
            format!("{}", config.font.horizontal_spacing),
            window,
            cx,
            &mut input_subscriptions,
        );
        section_focus_targets
            .entry(BuiltinSection::Font)
            .or_default()
            .push(horizontal_spacing_fh);
        let (opacity_input, opacity_fh) = Self::new_text_field(
            "0.1 – 1.0",
            format!("{}", config.window.opacity),
            window,
            cx,
            &mut input_subscriptions,
        );
        section_focus_targets
            .entry(BuiltinSection::Window)
            .or_default()
            .push(opacity_fh);
        let (scrollback_input, scrollback_fh) = Self::new_text_field(
            "e.g. 10000",
            format!("{}", config.scrollback.max_rows),
            window,
            cx,
            &mut input_subscriptions,
        );
        section_focus_targets
            .entry(BuiltinSection::Terminal)
            .or_default()
            .push(scrollback_fh);
        let (inset_x_input, inset_x_fh) = Self::new_text_field(
            "e.g. 4",
            format!("{}", config.font.inset_x),
            window,
            cx,
            &mut input_subscriptions,
        );
        section_focus_targets
            .entry(BuiltinSection::Terminal)
            .or_default()
            .push(inset_x_fh);
        let (inset_y_input, inset_y_fh) = Self::new_text_field(
            "e.g. 2",
            format!("{}", config.font.inset_y),
            window,
            cx,
            &mut input_subscriptions,
        );
        section_focus_targets
            .entry(BuiltinSection::Terminal)
            .or_default()
            .push(inset_y_fh);
        let (clipboard_streaming_input, clipboard_streaming_fh) = Self::new_text_field(
            "e.g. 10485760",
            format!("{}", config.clipboard.streaming_max_bytes),
            window,
            cx,
            &mut input_subscriptions,
        );
        section_focus_targets
            .entry(BuiltinSection::Clipboard)
            .or_default()
            .push(clipboard_streaming_fh);
        let (panels_grid_columns_input, panels_grid_columns_fh) = Self::new_text_field(
            "1 – 16",
            format!("{}", config.panels.grid_columns),
            window,
            cx,
            &mut input_subscriptions,
        );
        // Second (and last) text input on the merged Dock page — after
        // the Sidebar subsection's checkboxes (no text input) and before
        // the Bottom Dock subsection's own fields, so it's simply
        // appended to the same section's tab-cycle list.
        section_focus_targets
            .entry(BuiltinSection::Dock)
            .or_default()
            .push(panels_grid_columns_fh);
        // Never pre-filled with the real token (`default_value`) — a stored
        // secret is never re-displayed in a text field, so this field can't
        // go through `new_text_field` (which always sets a default value).
        // The "Token configured" status line covers presence instead.
        let telegram_token_input = cx.new(|cx_state| {
            InputState::new(window, cx_state)
                .placeholder(s::settings_telegram_token_placeholder())
                .masked(true)
        });
        input_subscriptions.push(Self::subscribe_input_state(
            &telegram_token_input,
            window,
            cx,
        ));
        section_focus_targets
            .entry(BuiltinSection::Notifications)
            .or_default()
            .push(telegram_token_input.read(cx).focus_handle(cx));
        let telegram_token_configured = crate::telegram::keychain::read_token().is_some();

        let cursor_style_str: SharedString = match config.cursor.style {
            daruda_config::CursorStyle::Block => "block".into(),
            daruda_config::CursorStyle::Underline => "underline".into(),
            daruda_config::CursorStyle::Bar => "bar".into(),
        };
        let cursor_style_select = cx.new(|cx| {
            select::state_with_options(
                vec![
                    SelectOption::new("block", s::settings_cursor_block()),
                    SelectOption::new("underline", s::settings_cursor_underline()),
                    SelectOption::new("bar", s::settings_cursor_bar()),
                ],
                Some(&cursor_style_str),
                window,
                cx,
            )
        });

        let permission_mode_str: SharedString =
            config.agent.default_permission_mode.mode_id().into();
        let default_permission_mode_select = cx.new(|cx| {
            use daruda_config::DefaultPermissionMode as M;
            // The dropdown shows just the bare mode id; the human-readable
            // explanation for the selected mode is rendered below the field
            // (see `render_agent`).
            let opts = M::ALL
                .into_iter()
                .map(|m| SelectOption::new(m.mode_id(), m.mode_id()))
                .collect();
            select::state_with_options(opts, Some(&permission_mode_str), window, cx)
        });

        let agent_preset = SharedString::from("codex-acp");
        let agent_preset_select = cx.new(|cx| {
            // Every built-in preset, launchable or not. A preset that needs a
            // manual install cannot become a row, so its label says so and the
            // section swaps the Add button for install instructions — hiding it
            // instead left the user with no sign the agent exists at all.
            let opts = daruda_config::agent_presets()
                .map(|preset| {
                    let label = match preset.launchability {
                        daruda_config::PresetLaunchability::Runnable { .. } => {
                            s::settings_agent_preset_option(preset.name, preset.id)
                        }
                        daruda_config::PresetLaunchability::NeedsManualInstall { .. } => {
                            s::settings_agent_preset_option_needs_install(preset.name, preset.id)
                        }
                    };
                    SelectOption::new(preset.id, label)
                })
                .collect();
            select::state_with_options(opts, Some(&agent_preset), window, cx)
        });

        // Entries that resolve get an editable row; entries that don't (a
        // preset id daruda no longer knows) have no fields to edit, so they are
        // held aside and written back untouched on save — a config the editor
        // cannot represent must not be a config the editor deletes.
        let mut agent_rows = Vec::with_capacity(config.agents.len());
        let mut agent_unresolved_entries = Vec::new();
        for entry in &config.agents {
            match entry.resolve() {
                Some(definition) => agent_rows.push(Self::agent_row_from_definition(
                    &definition,
                    entry.preset_id().map(str::to_string),
                    window,
                    cx,
                )),
                None => agent_unresolved_entries.push(entry.clone()),
            }
        }

        let max_fps_str: SharedString = config.render.max_fps.to_string().into();
        let max_fps_select = cx.new(|cx| {
            let opts = daruda_config::ALLOWED_MAX_FPS
                .iter()
                .map(|fps| {
                    SelectOption::new(
                        SharedString::from(fps.to_string()),
                        s::settings_max_fps_option(*fps),
                    )
                })
                .collect();
            select::state_with_options(opts, Some(&max_fps_str), window, cx)
        });

        // Resolve through the palette so a legacy / unknown stored value
        // (e.g. an old "base16-ocean.dark") still shows its effective
        // palette selected instead of a blank dropdown.
        let syntax_theme = SharedString::from(
            crate::ui::theme::SyntaxPalette::from_config_name(&config.file_viewer.syntax_theme)
                .config_name(),
        );
        let syntax_theme_select = cx.new(|cx| {
            let opts = SYNTAX_THEMES
                .iter()
                .map(|v| SelectOption::new(*v, syntax_theme_label(v)))
                .collect();
            select::state_with_options(opts, Some(&syntax_theme), window, cx)
        });

        // Theme dropdowns apply live on pick (no Save needed): the commit
        // persists just that one field, and the existing config fan-out
        // repaints every open editor / diff view / pane.
        input_subscriptions.push(cx.subscribe_in(
            &syntax_theme_select,
            window,
            |this, state, ev: &select::ConfirmEvent, _window, cx| {
                if matches!(ev, select::SelectEvent::Confirm(_)) {
                    this.persist_theme_field(state, |c, v| c.file_viewer.syntax_theme = v, cx);
                }
            },
        ));
        input_subscriptions.push(cx.subscribe_in(
            &terminal_preset_select,
            window,
            |this, state, ev: &select::ConfirmEvent, _window, cx| {
                if matches!(ev, select::SelectEvent::Confirm(_)) {
                    this.persist_theme_field(state, |c, v| c.theme.terminal_preset = v, cx);
                }
            },
        ));
        input_subscriptions.push(cx.subscribe_in(
            &ui_preset_select,
            window,
            |this, state, ev: &select::ConfirmEvent, _window, cx| {
                if matches!(ev, select::SelectEvent::Confirm(_)) {
                    this.persist_theme_field(state, |c, v| c.theme.ui_preset = v, cx);
                }
            },
        ));
        // The permission-mode dropdown is persisted on Save (not live), but
        // the explanatory text below it tracks the selection — repaint the
        // window on each pick so `render_agent` shows the matching blurb.
        input_subscriptions.push(cx.subscribe_in(
            &default_permission_mode_select,
            window,
            |_this, _state, ev: &select::ConfirmEvent, _window, cx| {
                if matches!(ev, select::SelectEvent::Confirm(_)) {
                    cx.notify();
                }
            },
        ));
        // Picking a preset swaps the Add button for install instructions when
        // that preset ships binaries only — repaint so the swap is immediate.
        input_subscriptions.push(cx.subscribe_in(
            &agent_preset_select,
            window,
            |_this, _state, ev: &select::ConfirmEvent, _window, cx| {
                if matches!(ev, select::SelectEvent::Confirm(_)) {
                    cx.notify();
                }
            },
        ));
        for row in &agent_rows {
            Self::subscribe_agent_row(row, window, cx, &mut input_subscriptions);
        }

        // First-field jump target for the Agent section (its full tab-cycle
        // list is dynamic — see `focus_next_input` — since rows are
        // added/removed at runtime).
        if let Some(row) = agent_rows.first() {
            section_focus_targets
                .entry(BuiltinSection::Agent)
                .or_default()
                .push(row.id_input.read(cx).focus_handle(cx));
        }

        let _updater_subscription =
            crate::update::Updater::get(cx).map(|e| cx.observe(&e, |_, _, cx| cx.notify()));

        // Managed accounts come from the app-wide Global (single source of
        // truth). Install it from disk if this window opened before any
        // Workspace (idempotent), then mirror the current value — refreshed
        // on change by `_accounts_global_subscription`.
        crate::workspace::accounts_global::install_if_absent(
            cx,
            daruda_store::accounts::load_accounts().unwrap_or_default(),
        );
        let accounts = crate::workspace::accounts_global::snapshot(cx);
        let _accounts_global_subscription = cx
            .observe_global::<crate::workspace::accounts_global::AccountsGlobal>(|this, cx| {
                this.accounts = crate::workspace::accounts_global::snapshot(cx);
                cx.notify();
            });

        let result = Self {
            panel_focus_handle: cx.focus_handle(),
            base_config: config.clone(),
            active_section: active,
            section_focus_targets,
            language_select,
            terminal_preset_select,
            ui_preset_select,
            font_family_select,
            font_size_input,
            editor_font_size_input,
            agent_chat_font_size_input,
            vertical_spacing_input,
            horizontal_spacing_input,
            cursor_style_select,
            cursor_blinking: config.cursor.blinking,
            default_permission_mode_select,
            agent_preset_select,
            agent_use_modifier_to_send: config.agent.use_modifier_to_send,
            agent_rows,
            agent_unresolved_entries,
            accounts,
            max_fps_select,
            close_pane_on_exit: config.shell.close_pane_on_exit,
            opacity_input,
            window_blur: config.window.blur,
            scrollback_input,
            inset_x_input,
            inset_y_input,
            files_show_hidden: config.left_dock.files_show_hidden,
            files_use_gitignore: config.left_dock.files_use_gitignore,
            syntax_theme_select,
            clipboard_streaming_input,
            panels_grid_columns_input,
            claude_status_enable: config.claude_status.enable,
            telegram_enabled: config.telegram.enabled,
            telegram_token_input,
            telegram_token_configured,
            telegram_pair_code: None,
            telegram_pair_command_copied: false,
            _telegram_pair_copy_revert_task: None,
            scroll_handle: gpui::ScrollHandle::new(),
            _input_subscriptions: input_subscriptions,
            error: None,
            plugin_ops_in_flight: std::collections::HashSet::new(),
            plugin_last_error: None,
            plugin_selected: None,
            plugin_view_skill: None,
            _skills_global_subscription: cx
                .observe_global::<crate::agent::skills::SkillsState>(|_, cx| cx.notify()),
            _accounts_global_subscription,
            _updater_subscription,
        };
        // The scroll handle is populated during prepaint, which runs after render.
        // Schedule a re-render so the scrollbar thumb appears on first display
        // without requiring an initial scroll event.
        cx.spawn(async move |this, cx| {
            this.update(cx, |_, cx| cx.notify()).ok();
        })
        .detach();

        // Track this window in the WindowRegistry so `open_settings_window`
        // can raise it instead of opening a second copy. The window's root
        // view is `gpui_component::Root` (the SettingsWindow needs Root in
        // the tree so `gpui_component::Input::TextElement::paint` can call
        // `Root::read` without panicking), so the registry stores a typed
        // `SettingsHandle` that bundles the window handle with a
        // `WeakEntity<SettingsWindow>` to recover the inner entity.
        let weak = cx.entity().downgrade();
        let window_handle = window.window_handle();
        WindowRegistry::register_settings(window_handle, weak, cx);
        cx.on_release(move |_: &mut SettingsWindow, cx: &mut gpui::App| {
            WindowRegistry::clear_settings(cx);
        })
        .detach();

        result
    }

    /// Switch the active page and (when applicable) land focus on the
    /// section's natural starting field. Called both by sidebar clicks
    /// and by `windows::open_settings_window` when a second open
    /// dispatch arrives while a Settings window is already alive.
    pub fn focus_section(
        &mut self,
        section: BuiltinSection,
        window: &mut Window,
        cx: &mut Context<Self>,
    ) {
        if self.active_section != section {
            self.active_section = section;
            // Reset scroll so the new section starts at the top —
            // otherwise switching from a long page leaves the new page
            // mid-scroll which is confusing.
            self.scroll_handle.set_offset(gpui::point(px(0.), px(0.)));
        }
        if let Some(fh) = self
            .section_focus_targets
            .get(&section)
            .and_then(|handles| handles.first())
            .cloned()
        {
            fh.focus(window, cx);
        } else {
            self.panel_focus_handle.focus(window, cx);
        }
        cx.notify();
    }

    pub fn active_section(&self) -> BuiltinSection {
        self.active_section
    }

    fn dismiss(&mut self, window: &mut Window) {
        window.remove_window();
    }

    /// Read, trim, and parse `input`'s value into `T`, rejecting values
    /// outside `range`. Collapses the "read → trim → parse → range filter →
    /// error" pattern repeated for every bounded numeric field below.
    fn parse_bounded_field<T: std::str::FromStr + PartialOrd>(
        input: &Entity<InputState>,
        range: impl RangeBounds<T>,
        err: impl FnOnce() -> SharedString,
        cx: &gpui::App,
    ) -> Result<T, SharedString> {
        input
            .read(cx)
            .value()
            .trim()
            .parse::<T>()
            .ok()
            .filter(|v| range.contains(v))
            .ok_or_else(err)
    }

    fn validate(&self, cx: &gpui::App) -> Result<daruda_config::Config, SharedString> {
        // Start from the snapshot taken at window-open time so fields not
        // exposed in the UI (e.g. [colors], [keybindings]) are preserved.
        let mut config = self.base_config.clone();

        config.general.language = self
            .language_select
            .read(cx)
            .selected_value()
            .map(|s| s.to_string())
            .unwrap_or_else(|| "auto".to_owned());

        config.theme.terminal_preset = self
            .terminal_preset_select
            .read(cx)
            .selected_value()
            .map(|s| s.to_string())
            .unwrap_or_else(|| "default".to_owned());

        config.theme.ui_preset = self
            .ui_preset_select
            .read(cx)
            .selected_value()
            .map(|s| s.to_string())
            .unwrap_or_else(|| daruda_config::ui_theme_presets::DEFAULT.to_owned());

        config.font.family = self
            .font_family_select
            .read(cx)
            .selected_value()
            .map(|s| s.to_string())
            .unwrap_or_else(|| daruda_config::FontConfig::default().family);

        config.font.size = Self::parse_bounded_field(
            &self.font_size_input,
            6.0..=72.0,
            || SharedString::from(s::settings_err_font_size()),
            cx,
        )?;
        config.font.editor_size = Self::parse_bounded_field(
            &self.editor_font_size_input,
            6.0..=72.0,
            || SharedString::from(s::settings_err_editor_font_size()),
            cx,
        )?;
        config.font.agent_chat_size = Self::parse_bounded_field(
            &self.agent_chat_font_size_input,
            6.0..=72.0,
            || SharedString::from(s::settings_err_agent_chat_font_size()),
            cx,
        )?;
        config.font.vertical_spacing = Self::parse_bounded_field(
            &self.vertical_spacing_input,
            0.5..=2.0,
            || SharedString::from(s::settings_err_spacing()),
            cx,
        )?;
        config.font.horizontal_spacing = Self::parse_bounded_field(
            &self.horizontal_spacing_input,
            0.5..=2.0,
            || SharedString::from(s::settings_err_spacing()),
            cx,
        )?;

        config.cursor.style = match self
            .cursor_style_select
            .read(cx)
            .selected_value()
            .map(|s| s.as_ref())
        {
            Some("underline") => daruda_config::CursorStyle::Underline,
            Some("bar") => daruda_config::CursorStyle::Bar,
            _ => daruda_config::CursorStyle::Block,
        };
        config.cursor.blinking = self.cursor_blinking;

        config.agent.default_permission_mode = self
            .default_permission_mode_select
            .read(cx)
            .selected_value()
            .and_then(|s| daruda_config::DefaultPermissionMode::from_mode_id(s.as_ref()))
            .unwrap_or_default();
        config.agent.use_modifier_to_send = self.agent_use_modifier_to_send;

        let mut agents = Vec::with_capacity(self.agent_rows.len());
        let mut seen_agent_ids = HashSet::new();
        for (index, row) in self.agent_rows.iter().enumerate() {
            let id = row.id_input.read(cx).value().trim().to_string();
            let name = row.name_input.read(cx).value().trim().to_string();
            let command = row.command_input.read(cx).value().trim().to_string();
            if id.is_empty() || name.is_empty() || command.is_empty() {
                return Err(SharedString::from(s::settings_err_agent_catalog_field(
                    index + 1,
                )));
            }
            if !is_valid_agent_id(&id) {
                return Err(SharedString::from(s::settings_err_agent_catalog_id(&id)));
            }
            if !seen_agent_ids.insert(id.clone()) {
                return Err(SharedString::from(s::settings_err_agent_catalog_duplicate(
                    &id,
                )));
            }

            let kind = row
                .transport_select
                .read(cx)
                .selected_value()
                .map(|v| v.to_string())
                .unwrap_or_else(|| "raw".to_string());
            let host = row.host_input.read(cx).value().trim().to_string();
            let container = row.container_input.read(cx).value().trim().to_string();
            if !agent_row_is_valid(&kind, &host, &container) {
                let msg = if kind == "ssh" {
                    s::settings_err_agent_catalog_host(index + 1)
                } else {
                    s::settings_err_agent_catalog_container(index + 1)
                };
                return Err(SharedString::from(msg));
            }

            let launch = match kind.as_str() {
                "ssh" => daruda_config::AgentLaunch::Ssh {
                    adapter_command: command,
                    host,
                },
                "docker" => daruda_config::AgentLaunch::Docker {
                    adapter_command: command,
                    container,
                },
                _ => daruda_config::AgentLaunch::Raw(command),
            };
            let default_mode = row.default_mode_input.read(cx).value().trim().to_string();
            let definition = daruda_config::AgentDefinition {
                id,
                name,
                launch,
                // Empty field = no override; the global default applies.
                default_mode: (!default_mode.is_empty()).then_some(default_mode),
            };
            // A row that came from a preset stays a reference to it, so the
            // fields the user left alone keep following the preset.
            agents.push(daruda_config::AgentEntry::for_definition(
                definition,
                row.preset.as_deref(),
            ));
        }
        if agents.is_empty() {
            return Err(SharedString::from(s::settings_err_agent_catalog_empty()));
        }
        agents.extend(self.agent_unresolved_entries.iter().cloned());
        config.agents = agents;

        config.render.max_fps = self
            .max_fps_select
            .read(cx)
            .selected_value()
            .and_then(|s| s.as_ref().parse::<u32>().ok())
            .unwrap_or(config.render.max_fps);
        config.render.clamp();

        config.shell.close_pane_on_exit = self.close_pane_on_exit;

        config.window.opacity = Self::parse_bounded_field(
            &self.opacity_input,
            0.1..=1.0,
            || SharedString::from(s::settings_err_opacity()),
            cx,
        )?;
        config.window.blur = self.window_blur;

        config.scrollback.max_rows = Self::parse_bounded_field(
            &self.scrollback_input,
            1_000..=500_000,
            || SharedString::from(s::settings_err_scrollback()),
            cx,
        )?;

        config.font.inset_x = Self::parse_bounded_field(
            &self.inset_x_input,
            0.0..=32.0,
            || SharedString::from(s::settings_err_inset()),
            cx,
        )?;
        config.font.inset_y = Self::parse_bounded_field(
            &self.inset_y_input,
            0.0..=32.0,
            || SharedString::from(s::settings_err_inset()),
            cx,
        )?;

        config.left_dock.files_show_hidden = self.files_show_hidden;
        config.left_dock.files_use_gitignore = self.files_use_gitignore;

        config.file_viewer.syntax_theme = self
            .syntax_theme_select
            .read(cx)
            .selected_value()
            .map(|s| s.to_string())
            .unwrap_or_else(|| daruda_config::FileViewerConfig::default().syntax_theme);

        config.clipboard.streaming_max_bytes = Self::parse_bounded_field(
            &self.clipboard_streaming_input,
            4_096..=67_108_864,
            || SharedString::from(s::settings_err_clipboard()),
            cx,
        )?;

        config.panels.grid_columns = Self::parse_bounded_field(
            &self.panels_grid_columns_input,
            1..=16,
            || SharedString::from(s::settings_err_grid_columns()),
            cx,
        )?;

        config.claude_status.enable = self.claude_status_enable;

        // `authorized_chat_id` is managed outside this form's staged-Save flow
        // (set asynchronously by the Telegram bridge's poll loop on a successful
        // pairing, or cleared immediately by the "Unpair" button) — re-read the
        // live value here instead of trusting `self.base_config`'s window-open
        // snapshot, so clicking Save can never revert a pairing that completed
        // while Settings was open.
        config.telegram.authorized_chat_id = crate::settings_store::SettingsStore::global(cx)
            .user_arc()
            .telegram
            .authorized_chat_id;
        config.telegram.enabled = self.telegram_enabled;

        Ok(config)
    }

    /// Persist a picked theme dropdown value immediately (no Save
    /// required). Writes only the one field `set` touches; `patch_user`'s
    /// fan-out then re-bridges themes and repaints open views, so the
    /// change is visible the moment the dropdown commits. `set` is a
    /// non-capturing fn so it coerces to a plain `fn` pointer.
    fn persist_theme_field(
        &mut self,
        select: &Entity<SelectState>,
        set: fn(&mut daruda_config::Config, String),
        cx: &mut Context<Self>,
    ) {
        let Some(value) = select.read(cx).selected_value().map(|s| s.to_string()) else {
            return;
        };
        use gpui::BorrowAppContext as _;
        let result = cx.update_global::<crate::settings_store::SettingsStore, _>(|store, _| {
            store.patch_user(|cfg| set(cfg, value.clone()))
        });
        if let Err(msg) = result {
            self.error = Some(SharedString::from(msg));
            cx.notify();
        }
    }

    fn submit(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        let config = match self.validate(cx) {
            Ok(c) => c,
            Err(msg) => {
                self.error = Some(msg);
                cx.notify();
                return;
            }
        };

        // `patch_user` persists the file, updates the Global, and
        // fires every `observe_global` subscriber on return — the
        // app-level theme/keybinding observer and each workspace's
        // own subscription fan the change out, keeping the in-memory
        // store in sync with disk in a single update cycle.
        use gpui::BorrowAppContext as _;
        let result = cx.update_global::<crate::settings_store::SettingsStore, _>(|store, _| {
            store.patch_user(|cfg| *cfg = config.clone())
        });
        if let Err(msg) = result {
            self.error = Some(SharedString::from(msg));
            cx.notify();
            return;
        }

        self.dismiss(window);
    }

    fn focus_next_input(&self, forward: bool, window: &mut Window, cx: &mut Context<Self>) {
        // Cycle only through inputs that belong to the *active* section
        // — Tab on the Font page must not jump into the Window page's
        // opacity input while it is hidden.
        let handles: Vec<FocusHandle> = if self.active_section == BuiltinSection::Agent {
            // Dynamic: rows are added/removed at runtime, so this section
            // can't be precomputed into `section_focus_targets` like the
            // fixed sections below.
            self.agent_rows
                .iter()
                .flat_map(|row| {
                    [
                        row.id_input.read(cx).focus_handle(cx),
                        row.name_input.read(cx).focus_handle(cx),
                        row.command_input.read(cx).focus_handle(cx),
                    ]
                })
                .collect()
        } else {
            // Sections with no text input (Cursor / Shell / placeholders /
            // …) have no entry in the map, so this falls through to the
            // `n == 0` early-return below.
            self.section_focus_targets
                .get(&self.active_section)
                .cloned()
                .unwrap_or_default()
        };
        let n = handles.len();
        if n == 0 {
            return;
        }
        let current = handles.iter().position(|h| h.is_focused(window));
        let next = if forward {
            current.map_or(0, |i| (i + 1) % n)
        } else {
            match current {
                Some(0) | None => n - 1,
                Some(i) => i - 1,
            }
        };
        handles[next].focus(window, cx);
    }

    pub(super) fn section_label(
        label: impl Into<gpui::SharedString>,
        cx: &gpui::App,
    ) -> impl IntoElement {
        div()
            .text_size(px(theme::LANE_SECTION_HEADER_FONT_SIZE))
            .text_color(theme::current(cx).text_muted)
            .mt(px(theme::MODAL_FOOTER_MARGIN_TOP))
            .child(label.into())
    }
}

/// Map config window settings to the GPUI window background appearance.
pub(crate) fn window_background_for(config: &daruda_config::Config) -> WindowBackgroundAppearance {
    if config.window.blur {
        WindowBackgroundAppearance::Blurred
    } else if config.window.opacity < 1.0 {
        WindowBackgroundAppearance::Transparent
    } else {
        WindowBackgroundAppearance::Opaque
    }
}

/// Curated syntax palettes. Value = config key resolved by
/// `palette::SyntaxPalette::from_config_name`; labels are i18n'd via
/// [`syntax_theme_label`]. The recommended Daruda palette is first.
const SYNTAX_THEMES: &[&str] = &[
    "daruda",
    "one-dark",
    "tokyo-night",
    "catppuccin-mocha",
    "dracula",
    "github-dark",
    "material-palenight",
    "monokai",
    "nord",
    "gruvbox-dark",
    "solarized-dark",
    "ayu-mirage",
    "night-owl",
    "darcula",
];

/// Localized display label for a syntax-palette config value.
fn syntax_theme_label(value: &str) -> String {
    match value {
        "one-dark" => s::settings_syntax_theme_one_dark(),
        "tokyo-night" => s::settings_syntax_theme_tokyo_night(),
        "catppuccin-mocha" => s::settings_syntax_theme_catppuccin_mocha(),
        "dracula" => s::settings_syntax_theme_dracula(),
        "github-dark" => s::settings_syntax_theme_github_dark(),
        "material-palenight" => s::settings_syntax_theme_material_palenight(),
        "monokai" => s::settings_syntax_theme_monokai(),
        "nord" => s::settings_syntax_theme_nord(),
        "gruvbox-dark" => s::settings_syntax_theme_gruvbox_dark(),
        "solarized-dark" => s::settings_syntax_theme_solarized_dark(),
        "ayu-mirage" => s::settings_syntax_theme_ayu_mirage(),
        "night-owl" => s::settings_syntax_theme_night_owl(),
        "darcula" => s::settings_syntax_theme_darcula(),
        _ => s::settings_syntax_theme_daruda(),
    }
}

fn is_valid_agent_id(id: &str) -> bool {
    !id.is_empty()
        && id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
}

/// Whether an agent catalog row's transport-specific fields are filled in.
/// `"ssh"` requires a non-blank `host`; `"docker"` requires a non-blank
/// `container`; any other `kind` (`"raw"`, or an unrecognized/absent select
/// value) has no extra requirement. Pure and GPUI-free so it is directly
/// unit-testable — the save loop in [`SettingsWindow::validate`] is the only
/// caller.
fn agent_row_is_valid(kind: &str, host: &str, container: &str) -> bool {
    match kind {
        "ssh" => !host.trim().is_empty(),
        "docker" => !container.trim().is_empty(),
        _ => true,
    }
}

/// The token [`agent_command_path_warning`] should look up on `PATH`, or
/// `None` when `command` means no local-PATH check applies.
///
/// No check applies when: the command is a JSON stdio config (self-contained,
/// no executable name to look up — same discrimination `daruda_config`'s
/// `AgentLaunch` uses to gate its own shell-string edits); or the first real
/// token (after stripping any `NAME=value` env-prefix assignments) is
/// `npx`/`uvx` — daruda provisions Node.js itself, and `uvx` resolves its own
/// Python venvs, so neither names a binary the user is expected to have
/// installed locally. Transport (ssh/docker exempts the whole row) is not
/// considered here — that suppression needs no `which` call, so it is applied
/// at render time instead (`sections::agent::render_agent_catalog_row`).
fn path_check_token(command: &str) -> Option<String> {
    let trimmed = command.trim();
    if trimmed.is_empty() || trimmed.starts_with('{') {
        return None;
    }
    let token = daruda_acp::node::first_command_token(trimmed)?;
    (!matches!(token.as_str(), "npx" | "uvx")).then_some(token)
}

/// The catalog row's local-PATH warning: `Some(token)` when
/// [`path_check_token`] says a check applies and that token is not found on
/// `PATH`, `None` otherwise (no check applies, or the binary was found).
/// Advisory only — a missing command never blocks
/// [`SettingsWindow::validate`], since registering an agent before
/// installing its CLI (or before adding it to `PATH`) is a legitimate flow.
fn agent_command_path_warning(command: &str) -> Option<String> {
    let token = path_check_token(command)?;
    which::which(&token).is_err().then_some(token)
}

/// Return all font family names available on this system, sorted alphabetically.
/// The `current` family is always included as the first entry so the select
/// can show the currently-configured font even if it is not yet installed.
fn all_font_names(cx: &gpui::App, current: &str) -> Vec<String> {
    let mut names = cx.text_system().all_font_names();
    names.sort();
    names.dedup();
    if !current.is_empty() && !names.iter().any(|n| n == current) {
        names.insert(0, current.to_owned());
    }
    names
}

// `render::*` is just the `impl Render for SettingsWindow` block —
// no items are re-exported, but keeping the module declaration above
// is what makes the impl visible to external callers.

#[cfg(test)]
mod agent_row_validation_tests {
    use super::agent_row_is_valid;

    #[test]
    fn ssh_requires_non_blank_host() {
        assert!(!agent_row_is_valid("ssh", "", ""));
        assert!(!agent_row_is_valid("ssh", "   ", ""));
        assert!(agent_row_is_valid("ssh", "vm-work", ""));
    }

    #[test]
    fn docker_requires_non_blank_container() {
        assert!(!agent_row_is_valid("docker", "", ""));
        assert!(!agent_row_is_valid("docker", "", "   "));
        assert!(agent_row_is_valid("docker", "", "ubuntu-dev"));
    }

    #[test]
    fn raw_is_always_valid_regardless_of_host_or_container() {
        assert!(agent_row_is_valid("raw", "", ""));
        assert!(agent_row_is_valid("raw", "irrelevant", "irrelevant"));
    }

    #[test]
    fn unrecognized_kind_is_treated_as_valid() {
        assert!(agent_row_is_valid("", "", ""));
        assert!(agent_row_is_valid("bogus", "", ""));
    }
}

#[cfg(test)]
mod agent_command_path_warning_tests {
    use super::{agent_command_path_warning, path_check_token};

    /// Never a real executable name, so `which` is guaranteed to miss it.
    const MISSING_COMMAND: &str = "daruda-settings-path-warning-test-missing-binary";

    #[test]
    fn npx_prefixed_commands_skip_the_check() {
        assert_eq!(path_check_token("npx -y some-pkg@latest --acp"), None);
    }

    #[test]
    fn uvx_prefixed_commands_skip_the_check() {
        assert_eq!(path_check_token("uvx some-pkg@latest -x"), None);
    }

    #[test]
    fn json_stdio_configs_skip_the_check() {
        assert_eq!(path_check_token(r#"{"command": "some-binary"}"#), None);
    }

    #[test]
    fn env_prefix_is_stripped_before_testing_the_launcher_token() {
        // The env-prefixed form of an npx preset (e.g. Augment) must not warn.
        assert_eq!(
            path_check_token("AUGMENT_DISABLE_AUTO_UPDATE=1 npx -y pkg@latest --acp"),
            None
        );
        // A plain local command behind an env prefix still gets checked.
        assert_eq!(
            path_check_token("FOO=1 my-local-cli acp"),
            Some("my-local-cli".to_string())
        );
    }

    #[test]
    fn a_plain_local_command_is_checked() {
        assert_eq!(
            path_check_token("my-local-cli acp"),
            Some("my-local-cli".to_string())
        );
    }

    #[test]
    fn a_command_found_on_path_gets_no_warning() {
        assert_eq!(agent_command_path_warning("sh -c true"), None);
    }

    #[test]
    fn a_command_missing_from_path_gets_a_warning() {
        assert_eq!(
            agent_command_path_warning(MISSING_COMMAND),
            Some(MISSING_COMMAND.to_string())
        );
    }

    #[test]
    fn npx_never_warns_even_when_npm_is_unavailable_in_the_test_sandbox() {
        assert_eq!(
            agent_command_path_warning("npx -y definitely-nonexistent-package@latest"),
            None
        );
    }
}
