use super::{SyntaxPalette, SyntaxTheme, TokenStyle, base16};

/// Dark-background variant for `palette` — the default editor lightness.
pub(super) fn dark_syntax_theme(palette: SyntaxPalette) -> SyntaxTheme {
    match palette {
        // Daruda — readability-tuned default. function / string_special
        // lifted out of the near-gray band; keyword + escape bold and
        // comment italic add non-color channels (R1).
        SyntaxPalette::Daruda => SyntaxTheme {
            keyword: base16(0xc6_78_dd),
            function: base16(0x82_aa_ff),
            type_: base16(0xeb_cb_8b),
            constant: base16(0xd0_87_70),
            string: base16(0xa3_be_8c),
            string_special: base16(0x7f_db_ca),
            tag: base16(0xbf_61_6a),
            tag_doctype: base16(0xab_79_67),
            comment: base16(0x65_73_7e),
            default: base16(0xc0_c5_ce),
            keyword_style: TokenStyle::BOLD,
            string_special_style: TokenStyle::BOLD,
            comment_style: TokenStyle::ITALIC,
        },
        // One Dark (Atom / zed) — color-only.
        SyntaxPalette::OneDark => SyntaxTheme {
            keyword: base16(0xc6_78_dd),
            function: base16(0x61_af_ef),
            type_: base16(0xe5_c0_7b),
            constant: base16(0xd1_9a_66),
            string: base16(0x98_c3_79),
            string_special: base16(0x56_b6_c2),
            tag: base16(0xe0_6c_75),
            tag_doctype: base16(0xbe_50_46),
            comment: base16(0x5c_63_70),
            default: base16(0xab_b2_bf),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::PLAIN,
        },
        // Tokyo Night — color + italic comments. The original comment
        // `#565f89` only reaches ~3.4x on near-black; lifted to `#6b74a3`
        // to clear the readability floor against daruda's background.
        SyntaxPalette::TokyoNight => SyntaxTheme {
            keyword: base16(0xbb_9a_f7),
            function: base16(0x7a_a2_f7),
            type_: base16(0x0d_b9_d7),
            constant: base16(0xff9e64),
            string: base16(0x9e_ce_6a),
            string_special: base16(0x89_dd_ff),
            tag: base16(0xf7_76_8e),
            tag_doctype: base16(0xff9e64),
            comment: base16(0x6b_74_a3),
            default: base16(0xc0_ca_f5),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::ITALIC,
        },
        // Catppuccin Mocha — color-only.
        SyntaxPalette::CatppuccinMocha => SyntaxTheme {
            keyword: base16(0xcb_a6_f7),
            function: base16(0x89_b4_fa),
            type_: base16(0xf9_e2_af),
            constant: base16(0xfa_b3_87),
            string: base16(0xa6_e3_a1),
            string_special: base16(0xf5_c2_e7),
            tag: base16(0xf3_8b_a8),
            tag_doctype: base16(0xeb_a0_ac),
            comment: base16(0x93_99_b2),
            default: base16(0xcd_d6_f4),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::PLAIN,
        },
        // Dracula — high-chroma, color-only.
        SyntaxPalette::Dracula => SyntaxTheme {
            keyword: base16(0xff_79_c6),
            function: base16(0x50_fa_7b),
            type_: base16(0x8b_e9_fd),
            constant: base16(0xbd_93_f9),
            string: base16(0xf1_fa_8c),
            string_special: base16(0xff_b8_6c),
            tag: base16(0xff_55_55),
            tag_doctype: base16(0x62_72_a4),
            comment: base16(0x62_72_a4),
            default: base16(0xf8_f8_f2),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::PLAIN,
        },
        // GitHub Dark — neutral; escapes bold (GitHub's own convention).
        SyntaxPalette::GitHubDark => SyntaxTheme {
            keyword: base16(0xff_7b_72),
            function: base16(0xd2_a8_ff),
            type_: base16(0xff_a6_57),
            constant: base16(0x79_c0_ff),
            string: base16(0xa5_d6_ff),
            string_special: base16(0xa5_d6_ff),
            tag: base16(0x7e_e7_87),
            tag_doctype: base16(0x7e_e7_87),
            comment: base16(0x8b_94_9e),
            default: base16(0xc9_d1_d9),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::BOLD,
            comment_style: TokenStyle::PLAIN,
        },
        // Material Palenight — calm purples/blues; italic comments.
        SyntaxPalette::MaterialPalenight => SyntaxTheme {
            keyword: base16(0xc7_92_ea),
            function: base16(0x82_aa_ff),
            type_: base16(0xff_cb_6b),
            constant: base16(0xf7_8c_6c),
            string: base16(0xc3_e8_8d),
            string_special: base16(0x89_dd_ff),
            tag: base16(0xff_55_72),
            tag_doctype: base16(0xff_55_72),
            comment: base16(0x69_70_98),
            default: base16(0xbf_c7_d5),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::ITALIC,
        },
        // Monokai — the Sublime classic; color-only.
        SyntaxPalette::Monokai => SyntaxTheme {
            keyword: base16(0xf9_26_72),
            function: base16(0xa6_e2_2e),
            type_: base16(0x66_d9_ef),
            constant: base16(0xae_81_ff),
            string: base16(0xe6_db_74),
            string_special: base16(0xae_81_ff),
            tag: base16(0xf9_26_72),
            tag_doctype: base16(0xf9_26_72),
            comment: base16(0x88_84_6f),
            default: base16(0xf8_f8_f2),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::PLAIN,
        },
        // Nord — muted arctic cool tones; comment lifted from nord3 (too
        // dim) to nord3's brighter editor variant for the near-black bg.
        SyntaxPalette::Nord => SyntaxTheme {
            keyword: base16(0x81_a1_c1),
            function: base16(0x88_c0_d0),
            type_: base16(0x8f_bc_bb),
            constant: base16(0xb4_8e_ad),
            string: base16(0xa3_be_8c),
            string_special: base16(0xeb_cb_8b),
            tag: base16(0xbf_61_6a),
            tag_doctype: base16(0xd0_87_70),
            comment: base16(0x61_6e_88),
            default: base16(0xd8_de_e9),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::PLAIN,
        },
        // Gruvbox Dark — warm retro; function uses aqua to stay distinct
        // from the green strings.
        SyntaxPalette::GruvboxDark => SyntaxTheme {
            keyword: base16(0xfb_49_34),
            function: base16(0x8e_c0_7c),
            type_: base16(0xfa_bd_2f),
            constant: base16(0xd3_86_9b),
            string: base16(0xb8_bb_26),
            string_special: base16(0xfe_80_19),
            tag: base16(0xfb_49_34),
            tag_doctype: base16(0xfe_80_19),
            comment: base16(0x92_83_74),
            default: base16(0xeb_db_b2),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::PLAIN,
        },
        // Solarized Dark — balanced; comment lifted base01 -> base00 to
        // clear the contrast floor on the near-black background.
        SyntaxPalette::SolarizedDark => SyntaxTheme {
            keyword: base16(0x85_99_00),
            function: base16(0x26_8b_d2),
            type_: base16(0xb5_89_00),
            constant: base16(0xd3_36_82),
            string: base16(0x2a_a1_98),
            string_special: base16(0xcb4b16),
            tag: base16(0x26_8b_d2),
            tag_doctype: base16(0x58_6e_75),
            comment: base16(0x65_7b_83),
            default: base16(0x83_94_96),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::PLAIN,
        },
        // Ayu Mirage — modern minimal; italic comments.
        SyntaxPalette::AyuMirage => SyntaxTheme {
            keyword: base16(0xff_a6_59),
            function: base16(0xff_cd_66),
            type_: base16(0x73_d0_ff),
            constant: base16(0xdf_bf_ff),
            string: base16(0xd5_ff_80),
            string_special: base16(0x95_e6_cb),
            tag: base16(0x5c_cf_e6),
            tag_doctype: base16(0x5c_cf_e6),
            comment: base16(0x6e_7c_8f),
            default: base16(0xcc_ca_c2),
            keyword_style: TokenStyle::PLAIN,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::ITALIC,
        },
        // Night Owl — italic keywords and comments.
        SyntaxPalette::NightOwl => SyntaxTheme {
            keyword: base16(0xc7_92_ea),
            function: base16(0x82_aa_ff),
            type_: base16(0xff_cb_8b),
            constant: base16(0xf7_8c_6c),
            string: base16(0xec_c4_8d),
            string_special: base16(0x7f_db_ca),
            tag: base16(0xca_ec_e6),
            tag_doctype: base16(0x63_77_77),
            comment: base16(0x63_77_77),
            default: base16(0xd6_de_eb),
            keyword_style: TokenStyle::ITALIC,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::ITALIC,
        },
        // Darcula — IntelliJ default; bold keywords (its signature).
        SyntaxPalette::Darcula => SyntaxTheme {
            keyword: base16(0xcc7832),
            function: base16(0xff_c6_6d),
            type_: base16(0xa9_b7_c6),
            constant: base16(0x98_76_aa),
            string: base16(0x6a_87_59),
            string_special: base16(0xcc7832),
            tag: base16(0xe8_bf_6a),
            tag_doctype: base16(0xe8_bf_6a),
            comment: base16(0x80_80_80),
            default: base16(0xa9_b7_c6),
            keyword_style: TokenStyle::BOLD,
            string_special_style: TokenStyle::PLAIN,
            comment_style: TokenStyle::PLAIN,
        },
    }
}
