//! Built-in ACP agent presets — the registry snapshot plus hand-curated
//! entries — and whether each one can be launched as it stands.

use super::{AgentDefinition, AgentLaunch};

/// Whether a preset can be launched right now. A registry `distribution` of
/// npx/uvx resolves to a single command line; a `binary` distribution ships
/// per-platform archives that would need a download, checksum and extract step
/// first, so daruda can only point the user at install instructions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PresetLaunchability {
    Runnable {
        command: &'static str,
    },
    /// `install_url` is the registry entry's `website`, falling back to its
    /// `repository` when it advertises no website.
    NeedsManualInstall {
        install_url: &'static str,
    },
}

/// A built-in ACP agent preset that can be offered to the user catalog.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentPreset {
    pub id: &'static str,
    pub name: &'static str,
    pub launchability: PresetLaunchability,
}

impl AgentPreset {
    /// The catalog entry this preset would insert, or `None` for
    /// [`PresetLaunchability::NeedsManualInstall`] — that preset has no launch
    /// command, so there is nothing to run yet.
    pub fn definition(self) -> Option<AgentDefinition> {
        let PresetLaunchability::Runnable { command } = self.launchability else {
            return None;
        };
        Some(AgentDefinition {
            id: self.id.to_string(),
            name: self.name.to_string(),
            launch: AgentLaunch::Raw(command.to_string()),
            // Presets carry no mode: daruda doesn't know what any given
            // registry adapter advertises, so the global default applies until
            // the user sets one.
            default_mode: None,
            // Presets carry no model either: the advertised list is
            // account/plan dependent, so there is nothing to pin ahead of a
            // real connection.
            default_model: None,
        })
    }
}

/// Every built-in preset: the registry block followed by the curated block.
pub fn presets() -> impl Iterator<Item = AgentPreset> {
    REGISTRY_PRESETS
        .iter()
        .copied()
        .chain(CURATED_PRESETS.iter().copied())
}

/// The built-in preset carrying `id`, whatever its launchability. Unlike
/// [`AgentDefinition::registry_preset`] this still finds a preset that needs a
/// manual install — the caller wants to say *why* it cannot be launched.
pub fn preset(id: &str) -> Option<AgentPreset> {
    presets().find(|preset| preset.id == id)
}

/// ACP registry snapshot used to seed the Settings preset list.
pub const ACP_REGISTRY_URL: &str =
    "https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json";

// BEGIN GENERATED by `cargo run -p gen_acp_presets` — edit the generator, not this.
/// Registry snapshot the block below was generated from.
pub const ACP_REGISTRY_VERSION: &str = "1.0.0";

/// Every agent in the [`ACP_REGISTRY_VERSION`] registry, sorted by id.
///
/// Each `Runnable` command pins `@latest` (npx dist-tag / uvx version alias)
/// rather than a specific version — same policy as
/// [`AgentDefinition::claude_default`]. Pinning a snapshot version here meant
/// every upstream release (new model, bugfix, protocol feature) needed a manual
/// PR to bump it — see the Codex GPT-5.6 rollout, where the pinned `codex-acp`
/// build predated the model by a week and it silently never showed up.
/// `@latest` trades that manual-bump tax for exposure to a bad upstream release
/// reaching every user simultaneously with no automatic rollback — accepted
/// here because `claude_default` already carries that same risk for daruda's
/// primary agent.
pub const REGISTRY_PRESETS: &[AgentPreset] = &[
    AgentPreset {
        id: "agoragentic-acp",
        name: "Agoragentic",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y agoragentic-mcp@latest --acp",
        },
    },
    AgentPreset {
        id: "amp-acp",
        name: "Amp",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://github.com/tao12345666333/amp-acp",
        },
    },
    AgentPreset {
        id: "auggie",
        name: "Auggie CLI",
        launchability: PresetLaunchability::Runnable {
            command: "AUGMENT_DISABLE_AUTO_UPDATE=1 npx -y @augmentcode/auggie@latest --acp",
        },
    },
    AgentPreset {
        id: "autohand",
        name: "Autohand Code",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @autohandai/autohand-acp@latest",
        },
    },
    AgentPreset {
        id: "claude-acp",
        name: "Claude Agent",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @agentclientprotocol/claude-agent-acp@latest",
        },
    },
    AgentPreset {
        id: "cline",
        name: "Cline",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y cline@latest --acp",
        },
    },
    AgentPreset {
        id: "codebuddy-code",
        name: "Codebuddy Code",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @tencent-ai/codebuddy-code@latest --acp",
        },
    },
    AgentPreset {
        id: "codex-acp",
        name: "Codex",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @agentclientprotocol/codex-acp@latest",
        },
    },
    AgentPreset {
        id: "cortex-code",
        name: "Cortex Code",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://docs.snowflake.com/en/user-guide/cortex-code/cortex-code",
        },
    },
    AgentPreset {
        id: "corust-agent",
        name: "Corust Agent",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://corust.ai/",
        },
    },
    AgentPreset {
        id: "crow-cli",
        name: "crow-cli",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://crow-ai.dev",
        },
    },
    AgentPreset {
        id: "cursor",
        name: "Cursor",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://cursor.com/docs/cli/acp",
        },
    },
    AgentPreset {
        id: "deepagents",
        name: "DeepAgents",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y deepagents-acp@latest",
        },
    },
    AgentPreset {
        id: "devin",
        name: "Devin",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://docs.devin.ai/cli",
        },
    },
    AgentPreset {
        id: "dimcode",
        name: "DimCode",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y dimcode@latest acp",
        },
    },
    AgentPreset {
        id: "dirac",
        name: "Dirac",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y dirac-cli@latest --acp",
        },
    },
    AgentPreset {
        id: "factory-droid",
        name: "Factory Droid",
        launchability: PresetLaunchability::Runnable {
            command: "DROID_DISABLE_AUTO_UPDATE=true FACTORY_DROID_AUTO_UPDATE_ENABLED=false npx -y droid@latest exec --output-format acp-daemon",
        },
    },
    AgentPreset {
        id: "fast-agent",
        name: "fast-agent",
        launchability: PresetLaunchability::Runnable {
            command: "uvx fast-agent-acp@latest -x",
        },
    },
    AgentPreset {
        id: "gemini",
        name: "Gemini CLI",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @google/gemini-cli@latest --acp",
        },
    },
    AgentPreset {
        id: "github-copilot-cli",
        name: "GitHub Copilot",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @github/copilot@latest --acp",
        },
    },
    AgentPreset {
        id: "glm-acp-agent",
        name: "GLM Agent",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y glm-acp-agent@latest",
        },
    },
    AgentPreset {
        id: "goose",
        name: "goose",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://block.github.io/goose/",
        },
    },
    AgentPreset {
        id: "grok-build",
        name: "Grok Build",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @xai-official/grok@latest agent stdio",
        },
    },
    AgentPreset {
        id: "harn",
        name: "Harn",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://harnlang.com",
        },
    },
    AgentPreset {
        id: "junie",
        name: "Junie",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://junie.jetbrains.com",
        },
    },
    AgentPreset {
        id: "kilo",
        name: "Kilo",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @kilocode/cli@latest acp",
        },
    },
    AgentPreset {
        id: "kimi",
        name: "Kimi CLI",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://moonshotai.github.io/kimi-cli/",
        },
    },
    AgentPreset {
        id: "minion-code",
        name: "Minion Code",
        launchability: PresetLaunchability::Runnable {
            command: "uvx minion-code@latest acp",
        },
    },
    AgentPreset {
        id: "mistral-vibe",
        name: "Mistral Vibe",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://mistral.ai/products/vibe",
        },
    },
    AgentPreset {
        id: "nova",
        name: "Nova",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @compass-ai/nova@latest acp",
        },
    },
    AgentPreset {
        id: "opencode",
        name: "OpenCode",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://opencode.ai",
        },
    },
    AgentPreset {
        id: "pi-acp",
        name: "pi ACP",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y pi-acp@latest",
        },
    },
    AgentPreset {
        id: "poolside",
        name: "Poolside",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://poolside.ai",
        },
    },
    AgentPreset {
        id: "qoder",
        name: "Qoder CLI",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @qoder-ai/qodercli@latest --acp",
        },
    },
    AgentPreset {
        id: "qwen-code",
        name: "Qwen Code",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @qwen-code/qwen-code@latest --acp --experimental-skills",
        },
    },
    AgentPreset {
        id: "sigit",
        name: "siGit Code",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @smbcloud/sigit@latest",
        },
    },
    AgentPreset {
        id: "stakpak",
        name: "Stakpak",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://stakpak.dev",
        },
    },
    AgentPreset {
        id: "vtcode",
        name: "VT Code",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://github.com/vinhnx/VTCode/blob/main/docs/guides/zed-acp.md",
        },
    },
];
// END GENERATED

/// Presets kept by hand, for agents the ACP registry does not list.
///
/// Admission rule: an entry belongs here only after someone actually connected
/// to it and ran one turn through daruda. Without that bar hand-curation rots
/// silently — the previous hand-transcribed table sat 15 agents behind the
/// registry with no signal that anything was missing.
pub const CURATED_PRESETS: &[AgentPreset] = &[];

#[cfg(test)]
mod tests {
    use super::*;

    /// `definition()` is what decides whether a preset can become a catalog row
    /// at all, so the Add button's behaviour rides on this being exactly
    /// "Some for Runnable, None for NeedsManualInstall".
    ///
    /// `install_url` is checked here rather than in the generator because it
    /// comes from the registry's own `website`/`repository` — upstream data we
    /// hand to `open_url` without reading it first.
    #[test]
    fn definition_follows_launchability() {
        for preset in presets() {
            match preset.launchability {
                PresetLaunchability::Runnable { command } => {
                    let definition = preset.definition().unwrap_or_else(|| {
                        panic!("{} is runnable so it has a definition", preset.id)
                    });
                    assert_eq!(definition.launch, AgentLaunch::Raw(command.to_string()));
                }
                PresetLaunchability::NeedsManualInstall { install_url } => {
                    assert!(
                        install_url.starts_with("https://"),
                        "{} install_url is not https: {install_url}",
                        preset.id
                    );
                    assert_eq!(preset.definition(), None, "{} cannot launch", preset.id);
                }
            }
        }
    }
}
