//! Built-in ACP agent presets — the registry snapshot plus hand-curated
//! entries — and whether each one can be launched as it stands.

use super::{AgentDefinition, AgentLaunch};

/// Whether a preset can be launched right now. A registry `distribution` of
/// npx/uvx resolves to a single command line; a `binary` distribution ships
/// per-platform archives that would need a download, checksum and extract step
/// first, so daruda can only point the user at install instructions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PresetLaunchability {
    Runnable {
        command: &'static str,
    },
    /// `install_url` is the registry entry's `website`, falling back to its
    /// `repository` when it advertises no website.
    NeedsManualInstall {
        install_url: &'static str,
    },
}

/// A built-in ACP agent preset that can be offered to the user catalog.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AgentPreset {
    pub id: &'static str,
    pub name: &'static str,
    /// The registry's one-line summary of the agent, empty when it gives none.
    pub description: &'static str,
    pub launchability: PresetLaunchability,
}

impl AgentPreset {
    /// The catalog entry this preset would insert, or `None` for
    /// [`PresetLaunchability::NeedsManualInstall`] — that preset has no launch
    /// command, so there is nothing to run yet.
    pub fn definition(self) -> Option<AgentDefinition> {
        let PresetLaunchability::Runnable { command } = self.launchability else {
            return None;
        };
        Some(AgentDefinition {
            // Presets carry no mode: daruda doesn't know what any given
            // registry adapter advertises, so the global default applies until
            // the user sets one.
            default_mode: None,
            // Presets carry no model either: the advertised list is
            // account/plan dependent, so there is nothing to pin ahead of a
            // real connection.
            default_model: None,
            // Nor any transcript-presentation default: those are a taste the
            // user states per agent, so the `[agent]` section applies until
            // they do.
            fold_mode: None,
            // Nor an environment, as a rule: what a given adapter needs to be
            // told is adapter-specific, so a preset states one only where
            // daruda knows the answer — looked up from the hand-maintained
            // table below the generated block.
            env: preset_env_default(self.id),
            ..AgentDefinition::new(
                self.id.to_string(),
                self.name.to_string(),
                AgentLaunch::Raw(command.to_string()),
            )
        })
    }
}

/// Every built-in preset: the registry block followed by the curated block.
pub fn presets() -> impl Iterator<Item = AgentPreset> {
    REGISTRY_PRESETS
        .iter()
        .copied()
        .chain(CURATED_PRESETS.iter().copied())
}

/// The built-in preset carrying `id`, whatever its launchability. Unlike
/// [`AgentDefinition::registry_preset`] this still finds a preset that needs a
/// manual install — the caller wants to say *why* it cannot be launched.
pub fn preset(id: &str) -> Option<AgentPreset> {
    presets().find(|preset| preset.id == id)
}

/// ACP registry snapshot used to seed the Settings preset list.
pub const ACP_REGISTRY_URL: &str =
    "https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json";

// BEGIN GENERATED by `cargo run -p gen_acp_presets` — edit the generator, not this.
/// Registry snapshot the block below was generated from.
pub const ACP_REGISTRY_VERSION: &str = "1.0.0";

/// Every agent in the [`ACP_REGISTRY_VERSION`] registry, sorted by id.
///
/// Each `Runnable` command pins `@latest` (npx dist-tag / uvx version alias)
/// rather than a specific version — same policy as
/// [`AgentDefinition::claude_default`]. Pinning a snapshot version here meant
/// every upstream release (new model, bugfix, protocol feature) needed a manual
/// PR to bump it — see the Codex GPT-5.6 rollout, where the pinned `codex-acp`
/// build predated the model by a week and it silently never showed up.
/// `@latest` trades that manual-bump tax for exposure to a bad upstream release
/// reaching every user simultaneously with no automatic rollback — accepted
/// here because `claude_default` already carries that same risk for daruda's
/// primary agent.
pub const REGISTRY_PRESETS: &[AgentPreset] = &[
    AgentPreset {
        id: "agoragentic-acp",
        name: "Agoragentic",
        description: "Agent marketplace with 174+ AI capabilities. Browse, invoke, and pay for agent services settled in USDC on Base L2.",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y agoragentic-mcp@latest --acp",
        },
    },
    AgentPreset {
        id: "amp-acp",
        name: "Amp",
        description: "ACP wrapper for Amp - the frontier coding agent",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://github.com/tao12345666333/amp-acp",
        },
    },
    AgentPreset {
        id: "auggie",
        name: "Auggie CLI",
        description: "Augment Code's powerful software agent, backed by industry-leading context engine",
        launchability: PresetLaunchability::Runnable {
            command: "AUGMENT_DISABLE_AUTO_UPDATE=1 npx -y @augmentcode/auggie@latest --acp",
        },
    },
    AgentPreset {
        id: "autohand",
        name: "Autohand Code",
        description: "Autohand Code - AI coding agent powered by Autohand AI",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @autohandai/autohand-acp@latest",
        },
    },
    AgentPreset {
        id: "claude-acp",
        name: "Claude Agent",
        description: "ACP wrapper for Anthropic's Claude",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @agentclientprotocol/claude-agent-acp@latest",
        },
    },
    AgentPreset {
        id: "cline",
        name: "Cline",
        description: "Autonomous coding agent CLI - capable of creating/editing files, running commands, using the browser, and more",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y cline@latest --acp",
        },
    },
    AgentPreset {
        id: "codebuddy-code",
        name: "Codebuddy Code",
        description: "Tencent Cloud's official intelligent coding tool",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @tencent-ai/codebuddy-code@latest --acp",
        },
    },
    AgentPreset {
        id: "codex-acp",
        name: "Codex",
        description: "ACP adapter for OpenAI's coding assistant",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @agentclientprotocol/codex-acp@latest",
        },
    },
    AgentPreset {
        id: "cortex-code",
        name: "Cortex Code",
        description: "Snowflake's Cortex Code coding agent",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://docs.snowflake.com/en/user-guide/cortex-code/cortex-code",
        },
    },
    AgentPreset {
        id: "corust-agent",
        name: "Corust Agent",
        description: "Co-building with a seasoned Rust partner.",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://corust.ai/",
        },
    },
    AgentPreset {
        id: "crow-cli",
        name: "crow-cli",
        description: "Minimal ACP Native Coding Agent",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://crow-ai.dev",
        },
    },
    AgentPreset {
        id: "cursor",
        name: "Cursor",
        description: "Cursor's coding agent",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://cursor.com/docs/cli/acp",
        },
    },
    AgentPreset {
        id: "deepagents",
        name: "DeepAgents",
        description: "Batteries-included AI coding and general purpose agent powered by LangChain.",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y deepagents-acp@latest",
        },
    },
    AgentPreset {
        id: "devin",
        name: "Devin",
        description: "Devin CLI coding agent by Cognition",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://docs.devin.ai/cli",
        },
    },
    AgentPreset {
        id: "dimcode",
        name: "DimCode",
        description: "A coding agent that puts leading models at your command.",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y dimcode@latest acp",
        },
    },
    AgentPreset {
        id: "dirac",
        name: "Dirac",
        description: "Reduces API costs by more than 50%, produces better and faster work. Uses Hash anchored parallel edits, AST manipulation and a whole lot of neat optimizations. Fully Open Source.",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y dirac-cli@latest --acp",
        },
    },
    AgentPreset {
        id: "factory-droid",
        name: "Factory Droid",
        description: "Factory Droid - AI coding agent powered by Factory AI",
        launchability: PresetLaunchability::Runnable {
            command: "DROID_DISABLE_AUTO_UPDATE=true FACTORY_DROID_AUTO_UPDATE_ENABLED=false npx -y droid@latest exec --output-format acp-daemon",
        },
    },
    AgentPreset {
        id: "fast-agent",
        name: "fast-agent",
        description: "Code and build agents with comprehensive multi-provider support",
        launchability: PresetLaunchability::Runnable {
            command: "uvx fast-agent-acp@latest -x",
        },
    },
    AgentPreset {
        id: "gemini",
        name: "Gemini CLI",
        description: "Google's official CLI for Gemini",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @google/gemini-cli@latest --acp",
        },
    },
    AgentPreset {
        id: "github-copilot-cli",
        name: "GitHub Copilot",
        description: "GitHub's AI pair programmer",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @github/copilot@latest --acp",
        },
    },
    AgentPreset {
        id: "glm-acp-agent",
        name: "GLM Agent",
        description: "ACP agent powered by Zhipu AI's GLM Coding Plan models (glm-5.1, glm-5-turbo, glm-4.7, glm-4.5-air). Supports streaming, tool calls, mid-session model switching, image input via Z.AI Coding Plan Vision MCP, and session load/fork/resume with on-disk persistence.",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y glm-acp-agent@latest",
        },
    },
    AgentPreset {
        id: "goose",
        name: "goose",
        description: "A local, extensible, open source AI agent that automates engineering tasks",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://block.github.io/goose/",
        },
    },
    AgentPreset {
        id: "grok-build",
        name: "Grok Build",
        description: "xAI's coding agent and CLI",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @xai-official/grok@latest agent stdio",
        },
    },
    AgentPreset {
        id: "harn",
        name: "Harn",
        description: "Harn runs .harn agent pipelines as a native ACP coding agent over stdio.",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://harnlang.com",
        },
    },
    AgentPreset {
        id: "junie",
        name: "Junie",
        description: "AI Coding Agent by JetBrains",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://junie.jetbrains.com",
        },
    },
    AgentPreset {
        id: "kilo",
        name: "Kilo",
        description: "The open source coding agent",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @kilocode/cli@latest acp",
        },
    },
    AgentPreset {
        id: "kimi",
        name: "Kimi CLI",
        description: "Moonshot AI's coding assistant",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://moonshotai.github.io/kimi-cli/",
        },
    },
    AgentPreset {
        id: "minion-code",
        name: "Minion Code",
        description: "An enhanced AI code assistant built on the Minion framework with rich development tools",
        launchability: PresetLaunchability::Runnable {
            command: "uvx minion-code@latest acp",
        },
    },
    AgentPreset {
        id: "mistral-vibe",
        name: "Mistral Vibe",
        description: "Mistral's open-source coding assistant",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://mistral.ai/products/vibe",
        },
    },
    AgentPreset {
        id: "nova",
        name: "Nova",
        description: "Nova by Compass AI - a fully-fledged software engineer at your command",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @compass-ai/nova@latest acp",
        },
    },
    AgentPreset {
        id: "opencode",
        name: "OpenCode",
        description: "The open source coding agent",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://opencode.ai",
        },
    },
    AgentPreset {
        id: "pi-acp",
        name: "pi ACP",
        description: "ACP adapter for pi coding agent",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y pi-acp@latest",
        },
    },
    AgentPreset {
        id: "poolside",
        name: "Poolside",
        description: "Poolside's coding agent",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://poolside.ai",
        },
    },
    AgentPreset {
        id: "qoder",
        name: "Qoder CLI",
        description: "AI coding assistant with agentic capabilities",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @qoder-ai/qodercli@latest --acp",
        },
    },
    AgentPreset {
        id: "qwen-code",
        name: "Qwen Code",
        description: "Alibaba's Qwen coding assistant",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @qwen-code/qwen-code@latest --acp --experimental-skills",
        },
    },
    AgentPreset {
        id: "sigit",
        name: "siGit Code",
        description: "Local-first coding agent. Runs entirely on your machine with optional on-device LLM inference via Onde.",
        launchability: PresetLaunchability::Runnable {
            command: "npx -y @smbcloud/sigit@latest",
        },
    },
    AgentPreset {
        id: "stakpak",
        name: "Stakpak",
        description: "Open-source DevOps agent in Rust with enterprise-grade security",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://stakpak.dev",
        },
    },
    AgentPreset {
        id: "vtcode",
        name: "VT Code",
        description: "An open-source coding agent with LLM-native code understanding and robust shell safety. Supports multiple LLM providers with automatic failover and efficient context management.",
        launchability: PresetLaunchability::NeedsManualInstall {
            install_url: "https://github.com/vinhnx/VTCode/blob/main/docs/guides/zed-acp.md",
        },
    },
];
// END GENERATED

/// Presets kept by hand, for agents the ACP registry does not list.
///
/// Admission rule: an entry belongs here only after someone actually connected
/// to it and ran one turn through daruda. Without that bar hand-curation rots
/// silently — the previous hand-transcribed table sat 15 agents behind the
/// registry with no signal that anything was missing.
pub const CURATED_PRESETS: &[AgentPreset] = &[];

/// The variable `codex-acp` reads its per-session config overlay from.
///
/// Public so a caller can ask whether a launch environment actually carries
/// the overlay, rather than matching on the preset id that happens to ship it
/// — the two coincide only because [`PRESET_ENV_DEFAULTS`] says so today.
pub const CODEX_CONFIG_ENV: &str = "CODEX_CONFIG";

/// The [`CODEX_CONFIG_ENV`] overlay `codex-acp` reads as a per-session config
/// object (`threadStart`/`threadResume`/`threadFork`), turning on codex's
/// native subagent reporting so a child tool call reaches the wire instead of
/// going out through legacy `spawnAgent` delegation, which daruda cannot show.
const CODEX_MULTI_AGENT_V2_CONFIG: &str = r#"{"features":{"multi_agent_v2":true}}"#;

/// Per-preset env defaults, hand-maintained beside [`CURATED_PRESETS`]: the
/// registry snapshot has no field for a daruda-side default and would drop it
/// on the next `gen_acp_presets` regeneration, so it cannot live in the
/// generated block above.
const PRESET_ENV_DEFAULTS: &[(&str, &[(&str, &str)])] = &[(
    "codex-acp",
    &[(CODEX_CONFIG_ENV, CODEX_MULTI_AGENT_V2_CONFIG)],
)];

/// The env `id` ships by default, or `None` when it names none — which is
/// what leaves a row referencing it free to state one of its own.
///
/// Canonicalized through [`super::canonical_env`], so the order the table
/// above happens to be written in never matters. A value read back from
/// `config.toml` is always key-sorted (`env` persists as a TOML table), and
/// `AgentEntry::reference` diffs a row's `env` against this one as a `Vec`:
/// were this side left in source order, two entries in non-alphabetical order
/// would compare unequal to a disk round trip that agrees with them in
/// content, and the row would freeze as an override.
fn preset_env_default(id: &str) -> Option<Vec<(String, String)>> {
    env_default_from(PRESET_ENV_DEFAULTS, id)
}

/// [`preset_env_default`] over an arbitrary table, so the canonicalization
/// can be tested on a multi-key entry — [`PRESET_ENV_DEFAULTS`] carries one
/// key today, which is exactly the case source order cannot get wrong.
fn env_default_from(table: &[(&str, &[(&str, &str)])], id: &str) -> Option<Vec<(String, String)>> {
    table
        .iter()
        .find(|(preset_id, _)| *preset_id == id)
        .map(|(_, env)| {
            super::canonical_env(
                env.iter()
                    .map(|(key, value)| ((*key).to_string(), (*value).to_string())),
            )
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `codex-acp` is the only preset with a daruda-stated env default today:
    /// turning on codex's native subagent reporting so a child tool call
    /// reaches daruda's agent chat instead of vanishing into legacy
    /// delegation. This is what makes an existing `codex-acp` catalog row
    /// pick the flag up with no config edit.
    #[test]
    fn codex_acp_preset_ships_the_multi_agent_v2_env_default() {
        let definition =
            AgentDefinition::registry_preset("codex-acp").expect("codex-acp is runnable");
        assert_eq!(
            definition.env,
            Some(vec![(
                "CODEX_CONFIG".to_string(),
                CODEX_MULTI_AGENT_V2_CONFIG.to_string(),
            )])
        );
    }

    /// The flag's whole effect lives in this one string, and codex reads it
    /// as JSON: a typo in the key, a wrong nesting or a stray brace makes the
    /// feature silently do nothing while every other test stays green.
    ///
    /// Pinned twice on purpose — the literal text (so a typo in the const has
    /// to be typed twice to pass) *and* the parsed structure (so a
    /// well-formed but wrongly-shaped overlay is caught even if both copies
    /// agree).
    #[test]
    fn the_multi_agent_v2_overlay_is_the_exact_json_codex_reads() {
        assert_eq!(
            CODEX_MULTI_AGENT_V2_CONFIG,
            r#"{"features":{"multi_agent_v2":true}}"#
        );

        let parsed: serde_json::Value =
            serde_json::from_str(CODEX_MULTI_AGENT_V2_CONFIG).expect("codex parses this as JSON");
        let root = parsed.as_object().expect("a JSON object");
        assert_eq!(
            root.keys().collect::<Vec<_>>(),
            vec!["features"],
            "an unexpected top-level key would be a different overlay"
        );
        let features = root["features"]
            .as_object()
            .expect("`features` is an object");
        assert_eq!(features.keys().collect::<Vec<_>>(), vec!["multi_agent_v2"]);
        assert_eq!(
            features["multi_agent_v2"],
            serde_json::Value::Bool(true),
            "the flag has to be the JSON boolean, not the string \"true\""
        );
    }

    /// The default stays "states none" — not "states an empty one" — for
    /// every preset not named in [`PRESET_ENV_DEFAULTS`]. The difference is
    /// what keeps such a row free to pick up a default added later.
    #[test]
    fn a_preset_without_an_env_default_states_none() {
        let definition = AgentDefinition::registry_preset("gemini").expect("gemini is runnable");
        assert_eq!(definition.env, None);
    }

    /// A typo'd id in [`PRESET_ENV_DEFAULTS`] would otherwise silently name no
    /// preset and do nothing — this fails loudly instead.
    ///
    /// Checked against [`AgentDefinition::registry_preset`], not [`preset`]:
    /// the latter also finds a `NeedsManualInstall` preset, whose
    /// [`AgentPreset::definition`] returns `None` before ever reading the env
    /// table — so a default parked on one of those is dead code that would
    /// still pass the looser check.
    #[test]
    fn every_preset_env_default_id_names_a_launchable_preset() {
        for (id, _) in PRESET_ENV_DEFAULTS {
            assert!(
                AgentDefinition::registry_preset(id).is_some(),
                "{id} in PRESET_ENV_DEFAULTS is not a launchable preset"
            );
        }
    }

    /// Every default is key-sorted, whatever order the table above is written
    /// in — the ordering `AgentEntry::reference`'s `Vec` diff needs to agree
    /// with what a disk round trip produces (`env` persists as a TOML table,
    /// so read-back is always key-ordered). Asserted on the whole table
    /// rather than on the one entry that exists today, so a second key added
    /// later is covered without anyone remembering to sort it.
    #[test]
    fn every_preset_env_default_is_canonically_ordered() {
        for (id, _) in PRESET_ENV_DEFAULTS {
            let env = preset_env_default(id).expect("the table names it");
            let mut sorted = env.clone();
            sorted.sort_by(|(a, _), (b, _)| a.cmp(b));
            assert_eq!(env, sorted, "{id}'s env default is not key-sorted");
        }
    }

    /// The case the real table cannot exercise yet: two keys written in
    /// non-alphabetical order. Left in source order, a row that agrees with
    /// the preset in *content* would compare unequal after a disk round trip
    /// and freeze as an override — the exact thing the promotion diff exists
    /// to prevent.
    #[test]
    fn a_multi_key_default_is_sorted_regardless_of_how_it_is_written() {
        const TABLE: &[(&str, &[(&str, &str)])] = &[("some-agent", &[("ZED", "3"), ("ABLE", "1")])];
        assert_eq!(
            env_default_from(TABLE, "some-agent"),
            Some(vec![
                ("ABLE".to_string(), "1".to_string()),
                ("ZED".to_string(), "3".to_string()),
            ])
        );
        assert_eq!(env_default_from(TABLE, "other-agent"), None);
    }

    /// `definition()` is what decides whether a preset can become a catalog row
    /// at all, so the Add button's behaviour rides on this being exactly
    /// "Some for Runnable, None for NeedsManualInstall".
    ///
    /// `install_url` is checked here rather than in the generator because it
    /// comes from the registry's own `website`/`repository` — upstream data we
    /// hand to `open_url` without reading it first.
    #[test]
    fn definition_follows_launchability() {
        for preset in presets() {
            match preset.launchability {
                PresetLaunchability::Runnable { command } => {
                    let definition = preset.definition().unwrap_or_else(|| {
                        panic!("{} is runnable so it has a definition", preset.id)
                    });
                    assert_eq!(definition.launch, AgentLaunch::Raw(command.to_string()));
                }
                PresetLaunchability::NeedsManualInstall { install_url } => {
                    assert!(
                        install_url.starts_with("https://"),
                        "{} install_url is not https: {install_url}",
                        preset.id
                    );
                    assert_eq!(preset.definition(), None, "{} cannot launch", preset.id);
                }
            }
        }
    }
}
