//! Generates the ACP registry preset block inside
//! `crates/daruda_config/src/agent/preset.rs` from a registry snapshot.
//!
//! Run `cargo run -p gen_acp_presets` to rewrite the block, or with `--check`
//! to fail when the committed block and the committed snapshot have drifted.
//! `scripts/sync-acp-registry.sh` refreshes the snapshot from the live registry
//! first; this binary never touches the network.

use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde::Deserialize;
use serde::de::{IgnoredAny, MapAccess, Visitor};

/// Only the span between these two lines is rewritten, so `CURATED_PRESETS`
/// and `ACP_REGISTRY_URL` outside it survive a regeneration.
const BEGIN_MARKER: &str =
    "// BEGIN GENERATED by `cargo run -p gen_acp_presets` — edit the generator, not this.";
const END_MARKER: &str = "// END GENERATED";

const REGISTRY_PRESETS_DOC: &str = "\
/// Every agent in the [`ACP_REGISTRY_VERSION`] registry, sorted by id.
///
/// Each `Runnable` command pins `@latest` (npx dist-tag / uvx version alias)
/// rather than a specific version — same policy as
/// [`AgentDefinition::claude_default`]. Pinning a snapshot version here meant
/// every upstream release (new model, bugfix, protocol feature) needed a manual
/// PR to bump it — see the Codex GPT-5.6 rollout, where the pinned `codex-acp`
/// build predated the model by a week and it silently never showed up.
/// `@latest` trades that manual-bump tax for exposure to a bad upstream release
/// reaching every user simultaneously with no automatic rollback — accepted
/// here because `claude_default` already carries that same risk for daruda's
/// primary agent.
";

/// Lines of drift context printed by `--check` per direction.
const DRIFT_LINE_BUDGET: usize = 20;

// ---------------------------------------------------------------------------
// Snapshot schema
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct Registry {
    version: String,
    agents: Vec<RegistryAgent>,
}

#[derive(Debug, Deserialize)]
struct RegistryAgent {
    id: String,
    name: String,
    repository: Option<String>,
    website: Option<String>,
    distribution: Distribution,
}

#[derive(Debug, Deserialize)]
struct Distribution {
    npx: Option<PackageRun>,
    uvx: Option<PackageRun>,
    /// Per-platform archives that daruda cannot launch as a command line, so
    /// only their presence matters here.
    binary: Option<IgnoredAny>,
}

#[derive(Debug, Deserialize)]
struct PackageRun {
    package: String,
    #[serde(default)]
    args: Vec<String>,
    #[serde(default)]
    env: OrderedEnv,
}

/// `env` as declared in the snapshot. Kept as an ordered list because the
/// generated command prefixes the pairs in the registry's own order, while
/// `serde_json::Map` would sort them unless the whole workspace opted into
/// `serde_json/preserve_order`.
#[derive(Debug, Default)]
struct OrderedEnv(Vec<(String, String)>);

impl<'de> Deserialize<'de> for OrderedEnv {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct OrderedEnvVisitor;

        impl<'de> Visitor<'de> for OrderedEnvVisitor {
            type Value = OrderedEnv;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                f.write_str("a map of environment variables")
            }

            fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<OrderedEnv, A::Error> {
                let mut pairs = Vec::new();
                while let Some(pair) = map.next_entry::<String, String>()? {
                    pairs.push(pair);
                }
                Ok(OrderedEnv(pairs))
            }
        }

        deserializer.deserialize_map(OrderedEnvVisitor)
    }
}

// ---------------------------------------------------------------------------
// Generated model
// ---------------------------------------------------------------------------

#[derive(Debug, PartialEq, Eq)]
enum Launchability {
    Runnable(String),
    NeedsManualInstall(String),
}

#[derive(Debug, PartialEq, Eq)]
struct Preset {
    id: String,
    name: String,
    launchability: Launchability,
}

#[derive(Debug, Clone, Copy)]
enum Runner {
    Npx,
    Uvx,
}

impl Runner {
    /// The launcher words that precede the package spec. `npx` needs `-y` so a
    /// missing package installs without an interactive prompt.
    fn prefix(self) -> &'static str {
        match self {
            Runner::Npx => "npx -y",
            Runner::Uvx => "uvx",
        }
    }
}

#[derive(Debug)]
enum GenError {
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    Json(serde_json::Error),
    MissingMarker {
        path: PathBuf,
        marker: String,
    },
    NoInstallUrl {
        id: String,
    },
    UnsupportedDistribution {
        id: String,
    },
}

impl fmt::Display for GenError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            GenError::Io { path, source } => write!(f, "{}: {source}", path.display()),
            GenError::Json(source) => write!(f, "malformed registry snapshot: {source}"),
            GenError::MissingMarker { path, marker } => {
                write!(f, "{} has no `{marker}` line", path.display())
            }
            GenError::NoInstallUrl { id } => write!(
                f,
                "`{id}` ships only binary archives but advertises neither a website nor a \
                 repository, so there is no install page to point the user at"
            ),
            GenError::UnsupportedDistribution { id } => write!(
                f,
                "`{id}` has no npx, uvx or binary distribution — teach the generator its shape"
            ),
        }
    }
}

impl std::error::Error for GenError {}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/// Drops whatever version the snapshot pinned and tracks the moving tag
/// instead. `==` is uvx/PEP 440; npm's separator is the *last* `@`, so a scoped
/// package keeps its leading one.
fn repin_latest(package: &str) -> String {
    let base = match package.find("==") {
        Some(sep) => &package[..sep],
        None => match package.rfind('@') {
            Some(sep) if sep > 0 => &package[..sep],
            _ => package,
        },
    };
    format!("{base}@latest")
}

fn command_line(runner: Runner, run: &PackageRun) -> String {
    let mut command = String::new();
    for (key, value) in &run.env.0 {
        command.push_str(key);
        command.push('=');
        command.push_str(value);
        command.push(' ');
    }
    command.push_str(runner.prefix());
    command.push(' ');
    command.push_str(&repin_latest(&run.package));
    for arg in &run.args {
        command.push(' ');
        command.push_str(arg);
    }
    command
}

fn launchability_of(agent: &RegistryAgent) -> Result<Launchability, GenError> {
    let runnable = match (&agent.distribution.npx, &agent.distribution.uvx) {
        (Some(run), _) => Some(command_line(Runner::Npx, run)),
        (None, Some(run)) => Some(command_line(Runner::Uvx, run)),
        (None, None) => None,
    };
    if let Some(command) = runnable {
        return Ok(Launchability::Runnable(command));
    }
    if agent.distribution.binary.is_none() {
        return Err(GenError::UnsupportedDistribution {
            id: agent.id.clone(),
        });
    }
    let install_url = agent
        .website
        .as_deref()
        .or(agent.repository.as_deref())
        .ok_or_else(|| GenError::NoInstallUrl {
            id: agent.id.clone(),
        })?;
    Ok(Launchability::NeedsManualInstall(install_url.to_string()))
}

fn presets_of(registry: &Registry) -> Result<Vec<Preset>, GenError> {
    let mut presets = registry
        .agents
        .iter()
        .map(|agent| {
            Ok(Preset {
                id: agent.id.clone(),
                name: agent.name.clone(),
                launchability: launchability_of(agent)?,
            })
        })
        .collect::<Result<Vec<_>, GenError>>()?;
    presets.sort_by(|a, b| a.id.cmp(&b.id));
    Ok(presets)
}

/// Renders `text` as a Rust string literal.
fn rust_str(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

fn render_block(registry: &Registry, presets: &[Preset]) -> String {
    let mut out = String::new();
    out.push_str(BEGIN_MARKER);
    out.push_str("\n/// Registry snapshot the block below was generated from.\n");
    out.push_str(&format!(
        "pub const ACP_REGISTRY_VERSION: &str = {};\n\n",
        rust_str(&registry.version)
    ));
    out.push_str(REGISTRY_PRESETS_DOC);
    out.push_str("pub const REGISTRY_PRESETS: &[AgentPreset] = &[\n");
    for preset in presets {
        out.push_str("    AgentPreset {\n");
        out.push_str(&format!("        id: {},\n", rust_str(&preset.id)));
        out.push_str(&format!("        name: {},\n", rust_str(&preset.name)));
        match &preset.launchability {
            Launchability::Runnable(command) => {
                out.push_str("        launchability: PresetLaunchability::Runnable {\n");
                out.push_str(&format!("            command: {},\n", rust_str(command)));
            }
            Launchability::NeedsManualInstall(install_url) => {
                out.push_str("        launchability: PresetLaunchability::NeedsManualInstall {\n");
                out.push_str(&format!(
                    "            install_url: {},\n",
                    rust_str(install_url)
                ));
            }
        }
        out.push_str("        },\n    },\n");
    }
    out.push_str("];\n");
    out.push_str(END_MARKER);
    out
}

// ---------------------------------------------------------------------------
// File splicing
// ---------------------------------------------------------------------------

fn read(path: &Path) -> Result<String, GenError> {
    fs::read_to_string(path).map_err(|source| GenError::Io {
        path: path.to_path_buf(),
        source,
    })
}

/// The byte range of the marker span, markers included.
fn marker_span(path: &Path, source: &str) -> Result<std::ops::Range<usize>, GenError> {
    let begin = source
        .find(BEGIN_MARKER)
        .ok_or_else(|| GenError::MissingMarker {
            path: path.to_path_buf(),
            marker: BEGIN_MARKER.to_string(),
        })?;
    let end = source[begin..]
        .find(END_MARKER)
        .ok_or_else(|| GenError::MissingMarker {
            path: path.to_path_buf(),
            marker: END_MARKER.to_string(),
        })?;
    Ok(begin..begin + end + END_MARKER.len())
}

fn splice(path: &Path, source: &str, block: &str) -> Result<String, GenError> {
    let span = marker_span(path, source)?;
    let mut spliced = String::with_capacity(source.len());
    spliced.push_str(&source[..span.start]);
    spliced.push_str(block);
    spliced.push_str(&source[span.end..]);
    Ok(spliced)
}

/// Human-readable drift: where the two texts first diverge, then the lines
/// unique to each side.
fn drift_report(current: &str, generated: &str) -> String {
    let mut report = String::new();
    let first_diff = current
        .lines()
        .zip(generated.lines())
        .position(|(a, b)| a != b)
        .unwrap_or_else(|| current.lines().count().min(generated.lines().count()));
    report.push_str(&format!(
        "first divergence at line {}\n",
        first_diff.saturating_add(1)
    ));

    let only_in = |left: &str, right: &str| -> Vec<String> {
        let kept: Vec<&str> = right.lines().collect();
        left.lines()
            .filter(|line| !kept.contains(line))
            .take(DRIFT_LINE_BUDGET)
            .map(str::to_string)
            .collect()
    };
    for line in only_in(current, generated) {
        report.push_str(&format!("-{line}\n"));
    }
    for line in only_in(generated, current) {
        report.push_str(&format!("+{line}\n"));
    }
    report
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

fn workspace_root() -> PathBuf {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("tools/<crate> sits two levels below the workspace root")
        .to_path_buf()
}

fn default_input() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("registry-snapshot.json")
}

fn preset_file() -> PathBuf {
    workspace_root().join("crates/daruda_config/src/agent/preset.rs")
}

struct Args {
    input: PathBuf,
    check: bool,
}

fn parse_args(argv: impl Iterator<Item = String>) -> Result<Args, String> {
    let mut input = None;
    let mut check = false;
    let mut argv = argv.peekable();
    while let Some(arg) = argv.next() {
        match arg.as_str() {
            "--check" => check = true,
            "--input" => {
                let value = argv.next().ok_or("--input needs a path")?;
                input = Some(PathBuf::from(value));
            }
            other => return Err(format!("unknown argument `{other}`")),
        }
    }
    Ok(Args {
        input: input.unwrap_or_else(default_input),
        check,
    })
}

/// Renders the preset file as the snapshot says it should look.
fn regenerate(input: &Path, target: &Path) -> Result<(String, String), GenError> {
    let registry: Registry = serde_json::from_str(&read(input)?).map_err(GenError::Json)?;
    let presets = presets_of(&registry)?;
    let current = read(target)?;
    let generated = splice(target, &current, &render_block(&registry, &presets))?;
    Ok((current, generated))
}

fn main() -> ExitCode {
    let args = match parse_args(std::env::args().skip(1)) {
        Ok(args) => args,
        Err(message) => {
            eprintln!("gen_acp_presets: {message}");
            eprintln!("usage: gen_acp_presets [--input <registry.json>] [--check]");
            return ExitCode::FAILURE;
        }
    };

    let target = preset_file();
    let (current, generated) = match regenerate(&args.input, &target) {
        Ok(pair) => pair,
        Err(error) => {
            eprintln!("gen_acp_presets: {error}");
            return ExitCode::FAILURE;
        }
    };

    if args.check {
        if current == generated {
            println!(
                "{} is in sync with {}",
                target.display(),
                args.input.display()
            );
            return ExitCode::SUCCESS;
        }
        eprintln!(
            "gen_acp_presets: {} has drifted from {} — run `cargo run -p gen_acp_presets`",
            target.display(),
            args.input.display()
        );
        eprint!("{}", drift_report(&current, &generated));
        return ExitCode::FAILURE;
    }

    if current == generated {
        println!("{} already up to date", target.display());
        return ExitCode::SUCCESS;
    }
    if let Err(source) = fs::write(&target, &generated) {
        eprintln!("gen_acp_presets: {}: {source}", target.display());
        return ExitCode::FAILURE;
    }
    println!("wrote {}", target.display());
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    fn agent(json: &str) -> RegistryAgent {
        serde_json::from_str(json).expect("test fixture parses")
    }

    fn command_of(json: &str) -> String {
        match launchability_of(&agent(json)).expect("fixture is launchable") {
            Launchability::Runnable(command) => command,
            other => panic!("expected a runnable command, got {other:?}"),
        }
    }

    fn install_url_of(json: &str) -> String {
        match launchability_of(&agent(json)).expect("fixture resolves") {
            Launchability::NeedsManualInstall(url) => url,
            other => panic!("expected a manual install, got {other:?}"),
        }
    }

    fn snapshot() -> Registry {
        serde_json::from_str(&read(&default_input()).expect("committed snapshot is readable"))
            .expect("committed snapshot parses")
    }

    #[test]
    fn repins_an_npm_version_to_the_dist_tag() {
        assert_eq!(repin_latest("codex-acp@1.1.7"), "codex-acp@latest");
    }

    #[test]
    fn repins_a_scoped_package_without_eating_its_leading_at() {
        assert_eq!(
            repin_latest("@augmentcode/auggie@0.34.0"),
            "@augmentcode/auggie@latest"
        );
        assert_eq!(
            repin_latest("@augmentcode/auggie"),
            "@augmentcode/auggie@latest"
        );
    }

    #[test]
    fn repins_a_uvx_equals_pin_to_the_dist_tag() {
        assert_eq!(
            repin_latest("fast-agent-acp==0.9.28"),
            "fast-agent-acp@latest"
        );
    }

    #[test]
    fn env_pairs_prefix_the_command_in_snapshot_order() {
        let command = command_of(
            r#"{ "id": "x", "name": "X", "distribution": { "npx": {
                 "package": "x@1.0.0",
                 "env": { "ZED": "1", "AUGMENT_DISABLE_AUTO_UPDATE": "1" } } } }"#,
        );
        assert_eq!(
            command, "ZED=1 AUGMENT_DISABLE_AUTO_UPDATE=1 npx -y x@latest",
            "declaration order must survive, not alphabetical order"
        );
    }

    #[test]
    fn args_join_onto_the_end_of_the_command() {
        let command = command_of(
            r#"{ "id": "x", "name": "X", "distribution": { "npx": {
                 "package": "x@1.0.0", "args": ["--acp", "--experimental-skills"] } } }"#,
        );
        assert_eq!(command, "npx -y x@latest --acp --experimental-skills");
    }

    #[test]
    fn uvx_runs_without_the_npx_yes_flag() {
        let command = command_of(
            r#"{ "id": "x", "name": "X", "distribution": { "uvx": {
                 "package": "x==1.0.0", "args": ["-x"] } } }"#,
        );
        assert_eq!(command, "uvx x@latest -x");
    }

    #[test]
    fn npx_wins_over_a_binary_distribution() {
        let command = command_of(
            r#"{ "id": "kilo", "name": "Kilo", "website": "https://kilo.ai/",
                 "distribution": { "binary": { "darwin-aarch64": { "cmd": "./kilo" } },
                                   "npx": { "package": "@kilocode/cli@7.4.17", "args": ["acp"] } } }"#,
        );
        assert_eq!(command, "npx -y @kilocode/cli@latest acp");
    }

    #[test]
    fn install_url_falls_back_to_the_repository_without_a_website() {
        let url = install_url_of(
            r#"{ "id": "amp-acp", "name": "Amp",
                 "repository": "https://github.com/tao12345666333/amp-acp",
                 "distribution": { "binary": {} } }"#,
        );
        assert_eq!(url, "https://github.com/tao12345666333/amp-acp");
    }

    #[test]
    fn install_url_uses_the_website_without_a_repository() {
        let url = install_url_of(
            r#"{ "id": "cursor", "name": "Cursor", "website": "https://cursor.com/docs/cli/acp",
                 "distribution": { "binary": {} } }"#,
        );
        assert_eq!(url, "https://cursor.com/docs/cli/acp");
    }

    #[test]
    fn a_binary_entry_with_no_install_page_fails_generation() {
        let error = launchability_of(&agent(
            r#"{ "id": "ghost", "name": "Ghost", "distribution": { "binary": {} } }"#,
        ))
        .expect_err("neither website nor repository must not silently become an empty url");
        assert!(
            matches!(&error, GenError::NoInstallUrl { id } if id == "ghost"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn an_unknown_distribution_shape_fails_generation() {
        let error = launchability_of(&agent(
            r#"{ "id": "ghost", "name": "Ghost", "website": "https://ghost.dev",
                 "distribution": {} }"#,
        ))
        .expect_err("an empty distribution is not a manual install");
        assert!(
            matches!(&error, GenError::UnsupportedDistribution { id } if id == "ghost"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn the_snapshot_yields_the_expected_launchability_split() {
        let presets = presets_of(&snapshot()).expect("every snapshot entry resolves");
        let runnable = presets
            .iter()
            .filter(|p| matches!(p.launchability, Launchability::Runnable(_)))
            .count();
        assert_eq!(presets.len(), 38);
        assert_eq!(runnable, 23);
    }

    #[test]
    fn the_generated_presets_are_sorted_and_unique_by_id() {
        let presets = presets_of(&snapshot()).expect("every snapshot entry resolves");
        let ids: Vec<&str> = presets.iter().map(|p| p.id.as_str()).collect();
        let mut expected = ids.clone();
        expected.sort_unstable();
        expected.dedup();
        assert_eq!(ids, expected);
    }

    /// Regression anchor: the committed block must be byte-identical to what the
    /// committed snapshot generates, so a hand edit to either side is caught
    /// without a network round-trip.
    #[test]
    fn the_committed_snapshot_reproduces_the_committed_preset_block() {
        let target = preset_file();
        let (current, generated) =
            regenerate(&default_input(), &target).expect("regeneration succeeds");
        assert!(
            current == generated,
            "{} has drifted:\n{}",
            target.display(),
            drift_report(&current, &generated)
        );
    }
}
